// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tse.Inputs
{

    public sealed class CngwStrategyConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("behavior")]
        public Input<Inputs.CngwStrategyConfigBehaviorGetArgs>? Behavior { get; set; }

        [Input("createTime")]
        public Input<string>? CreateTime { get; set; }

        [Input("maxReplicas")]
        public Input<int>? MaxReplicas { get; set; }

        [Input("metrics")]
        private InputList<Inputs.CngwStrategyConfigMetricGetArgs>? _metrics;
        public InputList<Inputs.CngwStrategyConfigMetricGetArgs> Metrics
        {
            get => _metrics ?? (_metrics = new InputList<Inputs.CngwStrategyConfigMetricGetArgs>());
            set => _metrics = value;
        }

        [Input("modifyTime")]
        public Input<string>? ModifyTime { get; set; }

        [Input("strategyId")]
        public Input<string>? StrategyId { get; set; }

        public CngwStrategyConfigGetArgs()
        {
        }
        public static new CngwStrategyConfigGetArgs Empty => new CngwStrategyConfigGetArgs();
    }
}
