// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tse.Inputs
{

    public sealed class CngwStrategyCronConfigParamGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("crontab")]
        public Input<string>? Crontab { get; set; }

        [Input("period")]
        public Input<string>? Period { get; set; }

        [Input("startAt")]
        public Input<string>? StartAt { get; set; }

        [Input("targetReplicas")]
        public Input<int>? TargetReplicas { get; set; }

        public CngwStrategyCronConfigParamGetArgs()
        {
        }
        public static new CngwStrategyCronConfigParamGetArgs Empty => new CngwStrategyCronConfigParamGetArgs();
    }
}
