// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class EditMediaOperationOutputStorage
    {
        public readonly Outputs.EditMediaOperationOutputStorageCosOutputStorage? CosOutputStorage;
        public readonly Outputs.EditMediaOperationOutputStorageS3OutputStorage? S3OutputStorage;
        public readonly string Type;

        [OutputConstructor]
        private EditMediaOperationOutputStorage(
            Outputs.EditMediaOperationOutputStorageCosOutputStorage? cosOutputStorage,

            Outputs.EditMediaOperationOutputStorageS3OutputStorage? s3OutputStorage,

            string type)
        {
            CosOutputStorage = cosOutputStorage;
            S3OutputStorage = s3OutputStorage;
            Type = type;
        }
    }
}
