// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class GetSchedulesScheduleInfoSetActivityResult
    {
        public readonly ImmutableArray<Outputs.GetSchedulesScheduleInfoSetActivityActivityParaResult> ActivityParas;
        public readonly string ActivityType;
        public readonly ImmutableArray<int> ReardriveIndices;

        [OutputConstructor]
        private GetSchedulesScheduleInfoSetActivityResult(
            ImmutableArray<Outputs.GetSchedulesScheduleInfoSetActivityActivityParaResult> activityParas,

            string activityType,

            ImmutableArray<int> reardriveIndices)
        {
            ActivityParas = activityParas;
            ActivityType = activityType;
            ReardriveIndices = reardriveIndices;
        }
    }
}
