// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class GetSchedulesScheduleInfoSetActivityActivityParaTranscodeTaskWatermarkSetResult
    {
        public readonly int Definition;
        public readonly double EndTimeOffset;
        public readonly ImmutableArray<Outputs.GetSchedulesScheduleInfoSetActivityActivityParaTranscodeTaskWatermarkSetRawParameterResult> RawParameters;
        public readonly double StartTimeOffset;
        public readonly string SvgContent;
        public readonly string TextContent;

        [OutputConstructor]
        private GetSchedulesScheduleInfoSetActivityActivityParaTranscodeTaskWatermarkSetResult(
            int definition,

            double endTimeOffset,

            ImmutableArray<Outputs.GetSchedulesScheduleInfoSetActivityActivityParaTranscodeTaskWatermarkSetRawParameterResult> rawParameters,

            double startTimeOffset,

            string svgContent,

            string textContent)
        {
            Definition = definition;
            EndTimeOffset = endTimeOffset;
            RawParameters = rawParameters;
            StartTimeOffset = startTimeOffset;
            SvgContent = svgContent;
            TextContent = textContent;
        }
    }
}
