// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class InputInputGroupSrtSettings
    {
        public readonly int? Latency;
        public readonly string? Mode;
        public readonly string? Passphrase;
        public readonly int? PbKeyLen;
        public readonly int? PeerIdleTimeout;
        public readonly int? PeerLatency;
        public readonly int? RecvLatency;
        public readonly ImmutableArray<Outputs.InputInputGroupSrtSettingsSourceAddress> SourceAddresses;
        public readonly string? StreamId;

        [OutputConstructor]
        private InputInputGroupSrtSettings(
            int? latency,

            string? mode,

            string? passphrase,

            int? pbKeyLen,

            int? peerIdleTimeout,

            int? peerLatency,

            int? recvLatency,

            ImmutableArray<Outputs.InputInputGroupSrtSettingsSourceAddress> sourceAddresses,

            string? streamId)
        {
            Latency = latency;
            Mode = mode;
            Passphrase = passphrase;
            PbKeyLen = pbKeyLen;
            PeerIdleTimeout = peerIdleTimeout;
            PeerLatency = peerLatency;
            RecvLatency = recvLatency;
            SourceAddresses = sourceAddresses;
            StreamId = streamId;
        }
    }
}
