// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class InputInputGroup
    {
        public readonly ImmutableArray<string> AllowIpLists;
        public readonly string? Description;
        public readonly string? FailOver;
        public readonly Outputs.InputInputGroupHlsPullSettings? HlsPullSettings;
        public readonly string InputName;
        public readonly string Protocol;
        public readonly Outputs.InputInputGroupResilientStream? ResilientStream;
        public readonly Outputs.InputInputGroupRtmpPullSettings? RtmpPullSettings;
        public readonly Outputs.InputInputGroupRtpSettings? RtpSettings;
        public readonly Outputs.InputInputGroupRtspPullSettings? RtspPullSettings;
        public readonly Outputs.InputInputGroupSrtSettings? SrtSettings;

        [OutputConstructor]
        private InputInputGroup(
            ImmutableArray<string> allowIpLists,

            string? description,

            string? failOver,

            Outputs.InputInputGroupHlsPullSettings? hlsPullSettings,

            string inputName,

            string protocol,

            Outputs.InputInputGroupResilientStream? resilientStream,

            Outputs.InputInputGroupRtmpPullSettings? rtmpPullSettings,

            Outputs.InputInputGroupRtpSettings? rtpSettings,

            Outputs.InputInputGroupRtspPullSettings? rtspPullSettings,

            Outputs.InputInputGroupSrtSettings? srtSettings)
        {
            AllowIpLists = allowIpLists;
            Description = description;
            FailOver = failOver;
            HlsPullSettings = hlsPullSettings;
            InputName = inputName;
            Protocol = protocol;
            ResilientStream = resilientStream;
            RtmpPullSettings = rtmpPullSettings;
            RtpSettings = rtpSettings;
            RtspPullSettings = rtspPullSettings;
            SrtSettings = srtSettings;
        }
    }
}
