// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class ProcessMediaOperationMediaProcessTask
    {
        public readonly ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskAdaptiveDynamicStreamingTaskSet> AdaptiveDynamicStreamingTaskSets;
        public readonly ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskAnimatedGraphicTaskSet> AnimatedGraphicTaskSets;
        public readonly ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskImageSpriteTaskSet> ImageSpriteTaskSets;
        public readonly ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskSampleSnapshotTaskSet> SampleSnapshotTaskSets;
        public readonly ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskSnapshotByTimeOffsetTaskSet> SnapshotByTimeOffsetTaskSets;
        public readonly ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSet> TranscodeTaskSets;

        [OutputConstructor]
        private ProcessMediaOperationMediaProcessTask(
            ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskAdaptiveDynamicStreamingTaskSet> adaptiveDynamicStreamingTaskSets,

            ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskAnimatedGraphicTaskSet> animatedGraphicTaskSets,

            ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskImageSpriteTaskSet> imageSpriteTaskSets,

            ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskSampleSnapshotTaskSet> sampleSnapshotTaskSets,

            ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskSnapshotByTimeOffsetTaskSet> snapshotByTimeOffsetTaskSets,

            ImmutableArray<Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSet> transcodeTaskSets)
        {
            AdaptiveDynamicStreamingTaskSets = adaptiveDynamicStreamingTaskSets;
            AnimatedGraphicTaskSets = animatedGraphicTaskSets;
            ImageSpriteTaskSets = imageSpriteTaskSets;
            SampleSnapshotTaskSets = sampleSnapshotTaskSets;
            SnapshotByTimeOffsetTaskSets = snapshotByTimeOffsetTaskSets;
            TranscodeTaskSets = transcodeTaskSets;
        }
    }
}
