// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Outputs
{

    [OutputType]
    public sealed class ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameter
    {
        public readonly Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameterAudioTemplate? AudioTemplate;
        public readonly string Container;
        public readonly int? RemoveAudio;
        public readonly int? RemoveVideo;
        public readonly Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameterTehdConfig? TehdConfig;
        public readonly Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameterVideoTemplate? VideoTemplate;

        [OutputConstructor]
        private ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameter(
            Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameterAudioTemplate? audioTemplate,

            string container,

            int? removeAudio,

            int? removeVideo,

            Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameterTehdConfig? tehdConfig,

            Outputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetRawParameterVideoTemplate? videoTemplate)
        {
            AudioTemplate = audioTemplate;
            Container = container;
            RemoveAudio = removeAudio;
            RemoveVideo = removeVideo;
            TehdConfig = tehdConfig;
            VideoTemplate = videoTemplate;
        }
    }
}
