// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Inputs
{

    public sealed class ContentReviewTemplatePornConfigureGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("asrReviewInfo")]
        public Input<Inputs.ContentReviewTemplatePornConfigureAsrReviewInfoGetArgs>? AsrReviewInfo { get; set; }

        [Input("imgReviewInfo")]
        public Input<Inputs.ContentReviewTemplatePornConfigureImgReviewInfoGetArgs>? ImgReviewInfo { get; set; }

        [Input("ocrReviewInfo")]
        public Input<Inputs.ContentReviewTemplatePornConfigureOcrReviewInfoGetArgs>? OcrReviewInfo { get; set; }

        public ContentReviewTemplatePornConfigureGetArgs()
        {
        }
        public static new ContentReviewTemplatePornConfigureGetArgs Empty => new ContentReviewTemplatePornConfigureGetArgs();
    }
}
