// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Inputs
{

    public sealed class FlowInputGroupRtpSettingsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("fec")]
        public Input<string>? Fec { get; set; }

        [Input("idleTimeout")]
        public Input<int>? IdleTimeout { get; set; }

        public FlowInputGroupRtpSettingsGetArgs()
        {
        }
        public static new FlowInputGroupRtpSettingsGetArgs Empty => new FlowInputGroupRtpSettingsGetArgs();
    }
}
