// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Inputs
{

    public sealed class ProcessMediaOperationMediaProcessTaskGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("adaptiveDynamicStreamingTaskSets")]
        private InputList<Inputs.ProcessMediaOperationMediaProcessTaskAdaptiveDynamicStreamingTaskSetGetArgs>? _adaptiveDynamicStreamingTaskSets;
        public InputList<Inputs.ProcessMediaOperationMediaProcessTaskAdaptiveDynamicStreamingTaskSetGetArgs> AdaptiveDynamicStreamingTaskSets
        {
            get => _adaptiveDynamicStreamingTaskSets ?? (_adaptiveDynamicStreamingTaskSets = new InputList<Inputs.ProcessMediaOperationMediaProcessTaskAdaptiveDynamicStreamingTaskSetGetArgs>());
            set => _adaptiveDynamicStreamingTaskSets = value;
        }

        [Input("animatedGraphicTaskSets")]
        private InputList<Inputs.ProcessMediaOperationMediaProcessTaskAnimatedGraphicTaskSetGetArgs>? _animatedGraphicTaskSets;
        public InputList<Inputs.ProcessMediaOperationMediaProcessTaskAnimatedGraphicTaskSetGetArgs> AnimatedGraphicTaskSets
        {
            get => _animatedGraphicTaskSets ?? (_animatedGraphicTaskSets = new InputList<Inputs.ProcessMediaOperationMediaProcessTaskAnimatedGraphicTaskSetGetArgs>());
            set => _animatedGraphicTaskSets = value;
        }

        [Input("imageSpriteTaskSets")]
        private InputList<Inputs.ProcessMediaOperationMediaProcessTaskImageSpriteTaskSetGetArgs>? _imageSpriteTaskSets;
        public InputList<Inputs.ProcessMediaOperationMediaProcessTaskImageSpriteTaskSetGetArgs> ImageSpriteTaskSets
        {
            get => _imageSpriteTaskSets ?? (_imageSpriteTaskSets = new InputList<Inputs.ProcessMediaOperationMediaProcessTaskImageSpriteTaskSetGetArgs>());
            set => _imageSpriteTaskSets = value;
        }

        [Input("sampleSnapshotTaskSets")]
        private InputList<Inputs.ProcessMediaOperationMediaProcessTaskSampleSnapshotTaskSetGetArgs>? _sampleSnapshotTaskSets;
        public InputList<Inputs.ProcessMediaOperationMediaProcessTaskSampleSnapshotTaskSetGetArgs> SampleSnapshotTaskSets
        {
            get => _sampleSnapshotTaskSets ?? (_sampleSnapshotTaskSets = new InputList<Inputs.ProcessMediaOperationMediaProcessTaskSampleSnapshotTaskSetGetArgs>());
            set => _sampleSnapshotTaskSets = value;
        }

        [Input("snapshotByTimeOffsetTaskSets")]
        private InputList<Inputs.ProcessMediaOperationMediaProcessTaskSnapshotByTimeOffsetTaskSetGetArgs>? _snapshotByTimeOffsetTaskSets;
        public InputList<Inputs.ProcessMediaOperationMediaProcessTaskSnapshotByTimeOffsetTaskSetGetArgs> SnapshotByTimeOffsetTaskSets
        {
            get => _snapshotByTimeOffsetTaskSets ?? (_snapshotByTimeOffsetTaskSets = new InputList<Inputs.ProcessMediaOperationMediaProcessTaskSnapshotByTimeOffsetTaskSetGetArgs>());
            set => _snapshotByTimeOffsetTaskSets = value;
        }

        [Input("transcodeTaskSets")]
        private InputList<Inputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetGetArgs>? _transcodeTaskSets;
        public InputList<Inputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetGetArgs> TranscodeTaskSets
        {
            get => _transcodeTaskSets ?? (_transcodeTaskSets = new InputList<Inputs.ProcessMediaOperationMediaProcessTaskTranscodeTaskSetGetArgs>());
            set => _transcodeTaskSets = value;
        }

        public ProcessMediaOperationMediaProcessTaskGetArgs()
        {
        }
        public static new ProcessMediaOperationMediaProcessTaskGetArgs Empty => new ProcessMediaOperationMediaProcessTaskGetArgs();
    }
}
