// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Inputs
{

    public sealed class ScheduleActivityActivityParaSampleSnapshotTaskArgs : global::Pulumi.ResourceArgs
    {
        [Input("definition", required: true)]
        public Input<int> Definition { get; set; } = null!;

        [Input("objectNumberFormat")]
        public Input<Inputs.ScheduleActivityActivityParaSampleSnapshotTaskObjectNumberFormatArgs>? ObjectNumberFormat { get; set; }

        [Input("outputObjectPath")]
        public Input<string>? OutputObjectPath { get; set; }

        [Input("outputStorage")]
        public Input<Inputs.ScheduleActivityActivityParaSampleSnapshotTaskOutputStorageArgs>? OutputStorage { get; set; }

        [Input("watermarkSets")]
        private InputList<Inputs.ScheduleActivityActivityParaSampleSnapshotTaskWatermarkSetArgs>? _watermarkSets;
        public InputList<Inputs.ScheduleActivityActivityParaSampleSnapshotTaskWatermarkSetArgs> WatermarkSets
        {
            get => _watermarkSets ?? (_watermarkSets = new InputList<Inputs.ScheduleActivityActivityParaSampleSnapshotTaskWatermarkSetArgs>());
            set => _watermarkSets = value;
        }

        public ScheduleActivityActivityParaSampleSnapshotTaskArgs()
        {
        }
        public static new ScheduleActivityActivityParaSampleSnapshotTaskArgs Empty => new ScheduleActivityActivityParaSampleSnapshotTaskArgs();
    }
}
