// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Inputs
{

    public sealed class ScheduleActivityActivityParaTranscodeTaskHeadTailParameterGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("headSets")]
        private InputList<Inputs.ScheduleActivityActivityParaTranscodeTaskHeadTailParameterHeadSetGetArgs>? _headSets;
        public InputList<Inputs.ScheduleActivityActivityParaTranscodeTaskHeadTailParameterHeadSetGetArgs> HeadSets
        {
            get => _headSets ?? (_headSets = new InputList<Inputs.ScheduleActivityActivityParaTranscodeTaskHeadTailParameterHeadSetGetArgs>());
            set => _headSets = value;
        }

        [Input("tailSets")]
        private InputList<Inputs.ScheduleActivityActivityParaTranscodeTaskHeadTailParameterTailSetGetArgs>? _tailSets;
        public InputList<Inputs.ScheduleActivityActivityParaTranscodeTaskHeadTailParameterTailSetGetArgs> TailSets
        {
            get => _tailSets ?? (_tailSets = new InputList<Inputs.ScheduleActivityActivityParaTranscodeTaskHeadTailParameterTailSetGetArgs>());
            set => _tailSets = value;
        }

        public ScheduleActivityActivityParaTranscodeTaskHeadTailParameterGetArgs()
        {
        }
        public static new ScheduleActivityActivityParaTranscodeTaskHeadTailParameterGetArgs Empty => new ScheduleActivityActivityParaTranscodeTaskHeadTailParameterGetArgs();
    }
}
