// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Mps.Inputs
{

    public sealed class ScheduleActivityActivityParaTranscodeTaskWatermarkSetArgs : global::Pulumi.ResourceArgs
    {
        [Input("definition", required: true)]
        public Input<int> Definition { get; set; } = null!;

        [Input("endTimeOffset")]
        public Input<double>? EndTimeOffset { get; set; }

        [Input("rawParameter")]
        public Input<Inputs.ScheduleActivityActivityParaTranscodeTaskWatermarkSetRawParameterArgs>? RawParameter { get; set; }

        [Input("startTimeOffset")]
        public Input<double>? StartTimeOffset { get; set; }

        [Input("svgContent")]
        public Input<string>? SvgContent { get; set; }

        [Input("textContent")]
        public Input<string>? TextContent { get; set; }

        public ScheduleActivityActivityParaTranscodeTaskWatermarkSetArgs()
        {
        }
        public static new ScheduleActivityActivityParaTranscodeTaskWatermarkSetArgs Empty => new ScheduleActivityActivityParaTranscodeTaskWatermarkSetArgs();
    }
}
