// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.ApiGateway.Inputs
{

    public sealed class ImportOpenApiResponseErrorCodeArgs : global::Pulumi.ResourceArgs
    {
        [Input("code")]
        public Input<int>? Code { get; set; }

        [Input("convertedCode")]
        public Input<int>? ConvertedCode { get; set; }

        [Input("desc")]
        public Input<string>? Desc { get; set; }

        [Input("msg")]
        public Input<string>? Msg { get; set; }

        [Input("needConvert")]
        public Input<bool>? NeedConvert { get; set; }

        public ImportOpenApiResponseErrorCodeArgs()
        {
        }
        public static new ImportOpenApiResponseErrorCodeArgs Empty => new ImportOpenApiResponseErrorCodeArgs();
    }
}
