// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Kubernetes.Outputs
{

    [OutputType]
    public sealed class GetClusterInstancesInstanceSetInstanceAdvancedSettingResult
    {
        public readonly ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingDataDiskResult> DataDisks;
        public readonly int DesiredPodNumber;
        public readonly string DockerGraphPath;
        public readonly ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingExtraArgResult> ExtraArgs;
        public readonly ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingGpuArgResult> GpuArgs;
        public readonly ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingLabelResult> Labels;
        public readonly string MountTarget;
        public readonly string PreStartUserScript;
        public readonly ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingTaintResult> Taints;
        public readonly int Unschedulable;
        public readonly string UserScript;

        [OutputConstructor]
        private GetClusterInstancesInstanceSetInstanceAdvancedSettingResult(
            ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingDataDiskResult> dataDisks,

            int desiredPodNumber,

            string dockerGraphPath,

            ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingExtraArgResult> extraArgs,

            ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingGpuArgResult> gpuArgs,

            ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingLabelResult> labels,

            string mountTarget,

            string preStartUserScript,

            ImmutableArray<Outputs.GetClusterInstancesInstanceSetInstanceAdvancedSettingTaintResult> taints,

            int unschedulable,

            string userScript)
        {
            DataDisks = dataDisks;
            DesiredPodNumber = desiredPodNumber;
            DockerGraphPath = dockerGraphPath;
            ExtraArgs = extraArgs;
            GpuArgs = gpuArgs;
            Labels = labels;
            MountTarget = mountTarget;
            PreStartUserScript = preStartUserScript;
            Taints = taints;
            Unschedulable = unschedulable;
            UserScript = userScript;
        }
    }
}
