// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Kubernetes.Outputs
{

    [OutputType]
    public sealed class NativeNodePoolNativeDataDisk
    {
        public readonly bool AutoFormatAndMount;
        public readonly string? DiskPartition;
        public readonly int DiskSize;
        public readonly string DiskType;
        public readonly string? Encrypt;
        public readonly string? FileSystem;
        public readonly string? KmsKeyId;
        public readonly string? MountTarget;
        public readonly string? SnapshotId;
        public readonly int? ThroughputPerformance;

        [OutputConstructor]
        private NativeNodePoolNativeDataDisk(
            bool autoFormatAndMount,

            string? diskPartition,

            int diskSize,

            string diskType,

            string? encrypt,

            string? fileSystem,

            string? kmsKeyId,

            string? mountTarget,

            string? snapshotId,

            int? throughputPerformance)
        {
            AutoFormatAndMount = autoFormatAndMount;
            DiskPartition = diskPartition;
            DiskSize = diskSize;
            DiskType = diskType;
            Encrypt = encrypt;
            FileSystem = fileSystem;
            KmsKeyId = kmsKeyId;
            MountTarget = mountTarget;
            SnapshotId = snapshotId;
            ThroughputPerformance = throughputPerformance;
        }
    }
}
