// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Teo.Inputs
{

    public sealed class AccelerationDomainOriginInfoGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("backupOrigin")]
        public Input<string>? BackupOrigin { get; set; }

        [Input("origin", required: true)]
        public Input<string> Origin { get; set; } = null!;

        [Input("originType", required: true)]
        public Input<string> OriginType { get; set; } = null!;

        [Input("privateAccess")]
        public Input<string>? PrivateAccess { get; set; }

        [Input("privateParameters")]
        private InputList<Inputs.AccelerationDomainOriginInfoPrivateParameterGetArgs>? _privateParameters;
        public InputList<Inputs.AccelerationDomainOriginInfoPrivateParameterGetArgs> PrivateParameters
        {
            get => _privateParameters ?? (_privateParameters = new InputList<Inputs.AccelerationDomainOriginInfoPrivateParameterGetArgs>());
            set => _privateParameters = value;
        }

        public AccelerationDomainOriginInfoGetArgs()
        {
        }
        public static new AccelerationDomainOriginInfoGetArgs Empty => new AccelerationDomainOriginInfoGetArgs();
    }
}
