// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getAttackOverview(args: GetAttackOverviewArgs, opts?: pulumi.InvokeOptions): Promise<GetAttackOverviewResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Waf/getAttackOverview:getAttackOverview", {
        "appid": args.appid,
        "domain": args.domain,
        "edition": args.edition,
        "fromTime": args.fromTime,
        "instanceId": args.instanceId,
        "resultOutputFile": args.resultOutputFile,
        "toTime": args.toTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getAttackOverview.
 */
export interface GetAttackOverviewArgs {
    appid?: number;
    domain?: string;
    edition?: string;
    fromTime: string;
    instanceId?: string;
    resultOutputFile?: string;
    toTime: string;
}

/**
 * A collection of values returned by getAttackOverview.
 */
export interface GetAttackOverviewResult {
    readonly accessCount: number;
    readonly aclCount: number;
    readonly apiAssetsCount: number;
    readonly apiRiskEventCount: number;
    readonly appid?: number;
    readonly attackCount: number;
    readonly botCount: number;
    readonly ccCount: number;
    readonly domain?: string;
    readonly edition?: string;
    readonly fromTime: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId?: string;
    readonly resultOutputFile?: string;
    readonly toTime: string;
}
export function getAttackOverviewOutput(args: GetAttackOverviewOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAttackOverviewResult> {
    return pulumi.output(args).apply((a: any) => getAttackOverview(a, opts))
}

/**
 * A collection of arguments for invoking getAttackOverview.
 */
export interface GetAttackOverviewOutputArgs {
    appid?: pulumi.Input<number>;
    domain?: pulumi.Input<string>;
    edition?: pulumi.Input<string>;
    fromTime: pulumi.Input<string>;
    instanceId?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
    toTime: pulumi.Input<string>;
}
