// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getAttackTotalCount(args: GetAttackTotalCountArgs, opts?: pulumi.InvokeOptions): Promise<GetAttackTotalCountResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Waf/getAttackTotalCount:getAttackTotalCount", {
        "domain": args.domain,
        "endTime": args.endTime,
        "queryString": args.queryString,
        "resultOutputFile": args.resultOutputFile,
        "startTime": args.startTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getAttackTotalCount.
 */
export interface GetAttackTotalCountArgs {
    domain: string;
    endTime: string;
    queryString?: string;
    resultOutputFile?: string;
    startTime: string;
}

/**
 * A collection of values returned by getAttackTotalCount.
 */
export interface GetAttackTotalCountResult {
    readonly domain: string;
    readonly endTime: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly queryString?: string;
    readonly resultOutputFile?: string;
    readonly startTime: string;
    readonly totalCount: number;
}
export function getAttackTotalCountOutput(args: GetAttackTotalCountOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAttackTotalCountResult> {
    return pulumi.output(args).apply((a: any) => getAttackTotalCount(a, opts))
}

/**
 * A collection of arguments for invoking getAttackTotalCount.
 */
export interface GetAttackTotalCountOutputArgs {
    domain: pulumi.Input<string>;
    endTime: pulumi.Input<string>;
    queryString?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
    startTime: pulumi.Input<string>;
}
