// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getCiphers(args?: GetCiphersArgs, opts?: pulumi.InvokeOptions): Promise<GetCiphersResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Waf/getCiphers:getCiphers", {
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getCiphers.
 */
export interface GetCiphersArgs {
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getCiphers.
 */
export interface GetCiphersResult {
    readonly ciphers: outputs.Waf.GetCiphersCipher[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly resultOutputFile?: string;
}
export function getCiphersOutput(args?: GetCiphersOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCiphersResult> {
    return pulumi.output(args).apply((a: any) => getCiphers(a, opts))
}

/**
 * A collection of arguments for invoking getCiphers.
 */
export interface GetCiphersOutputArgs {
    resultOutputFile?: pulumi.Input<string>;
}
