// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Wedata.Outputs
{

    [OutputType]
    public sealed class DqRuleCompareRuleItemValueList
    {
        public readonly string? Value;
        public readonly int? ValueType;

        [OutputConstructor]
        private DqRuleCompareRuleItemValueList(
            string? value,

            int? valueType)
        {
            Value = value;
            ValueType = valueType;
        }
    }
}
