// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cvm.Inputs
{

    public sealed class ActionTimerActionTimerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("actionTime")]
        public Input<string>? ActionTime { get; set; }

        [Input("timerAction")]
        public Input<string>? TimerAction { get; set; }

        public ActionTimerActionTimerGetArgs()
        {
        }
        public static new ActionTimerActionTimerGetArgs Empty => new ActionTimerActionTimerGetArgs();
    }
}
