// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Ssl
{
    public static class GetDescribeHostWafInstanceList
    {
        public static Task<GetDescribeHostWafInstanceListResult> InvokeAsync(GetDescribeHostWafInstanceListArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDescribeHostWafInstanceListResult>("tencentcloud:Ssl/getDescribeHostWafInstanceList:getDescribeHostWafInstanceList", args ?? new GetDescribeHostWafInstanceListArgs(), options.WithDefaults());

        public static Output<GetDescribeHostWafInstanceListResult> Invoke(GetDescribeHostWafInstanceListInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDescribeHostWafInstanceListResult>("tencentcloud:Ssl/getDescribeHostWafInstanceList:getDescribeHostWafInstanceList", args ?? new GetDescribeHostWafInstanceListInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDescribeHostWafInstanceListArgs : global::Pulumi.InvokeArgs
    {
        [Input("certificateId", required: true)]
        public string CertificateId { get; set; } = null!;

        [Input("filters")]
        private List<Inputs.GetDescribeHostWafInstanceListFilterArgs>? _filters;
        public List<Inputs.GetDescribeHostWafInstanceListFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetDescribeHostWafInstanceListFilterArgs>());
            set => _filters = value;
        }

        [Input("isCache")]
        public int? IsCache { get; set; }

        [Input("oldCertificateId")]
        public string? OldCertificateId { get; set; }

        [Input("resourceType", required: true)]
        public string ResourceType { get; set; } = null!;

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetDescribeHostWafInstanceListArgs()
        {
        }
        public static new GetDescribeHostWafInstanceListArgs Empty => new GetDescribeHostWafInstanceListArgs();
    }

    public sealed class GetDescribeHostWafInstanceListInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("certificateId", required: true)]
        public Input<string> CertificateId { get; set; } = null!;

        [Input("filters")]
        private InputList<Inputs.GetDescribeHostWafInstanceListFilterInputArgs>? _filters;
        public InputList<Inputs.GetDescribeHostWafInstanceListFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetDescribeHostWafInstanceListFilterInputArgs>());
            set => _filters = value;
        }

        [Input("isCache")]
        public Input<int>? IsCache { get; set; }

        [Input("oldCertificateId")]
        public Input<string>? OldCertificateId { get; set; }

        [Input("resourceType", required: true)]
        public Input<string> ResourceType { get; set; } = null!;

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetDescribeHostWafInstanceListInvokeArgs()
        {
        }
        public static new GetDescribeHostWafInstanceListInvokeArgs Empty => new GetDescribeHostWafInstanceListInvokeArgs();
    }


    [OutputType]
    public sealed class GetDescribeHostWafInstanceListResult
    {
        public readonly string CertificateId;
        public readonly ImmutableArray<Outputs.GetDescribeHostWafInstanceListFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetDescribeHostWafInstanceListInstanceListResult> InstanceLists;
        public readonly int? IsCache;
        public readonly string? OldCertificateId;
        public readonly string ResourceType;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetDescribeHostWafInstanceListResult(
            string certificateId,

            ImmutableArray<Outputs.GetDescribeHostWafInstanceListFilterResult> filters,

            string id,

            ImmutableArray<Outputs.GetDescribeHostWafInstanceListInstanceListResult> instanceLists,

            int? isCache,

            string? oldCertificateId,

            string resourceType,

            string? resultOutputFile)
        {
            CertificateId = certificateId;
            Filters = filters;
            Id = id;
            InstanceLists = instanceLists;
            IsCache = isCache;
            OldCertificateId = oldCertificateId;
            ResourceType = resourceType;
            ResultOutputFile = resultOutputFile;
        }
    }
}
