// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dlc

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCheckDataEngineImageCanBeRollback(ctx *pulumi.Context, args *GetCheckDataEngineImageCanBeRollbackArgs, opts ...pulumi.InvokeOption) (*GetCheckDataEngineImageCanBeRollbackResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCheckDataEngineImageCanBeRollbackResult
	err := ctx.Invoke("tencentcloud:Dlc/getCheckDataEngineImageCanBeRollback:getCheckDataEngineImageCanBeRollback", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCheckDataEngineImageCanBeRollback.
type GetCheckDataEngineImageCanBeRollbackArgs struct {
	DataEngineId     string  `pulumi:"dataEngineId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getCheckDataEngineImageCanBeRollback.
type GetCheckDataEngineImageCanBeRollbackResult struct {
	DataEngineId string `pulumi:"dataEngineId"`
	FromRecordId string `pulumi:"fromRecordId"`
	// The provider-assigned unique ID for this managed resource.
	Id               string  `pulumi:"id"`
	IsRollback       bool    `pulumi:"isRollback"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	ToRecordId       string  `pulumi:"toRecordId"`
}

func GetCheckDataEngineImageCanBeRollbackOutput(ctx *pulumi.Context, args GetCheckDataEngineImageCanBeRollbackOutputArgs, opts ...pulumi.InvokeOption) GetCheckDataEngineImageCanBeRollbackResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCheckDataEngineImageCanBeRollbackResult, error) {
			args := v.(GetCheckDataEngineImageCanBeRollbackArgs)
			r, err := GetCheckDataEngineImageCanBeRollback(ctx, &args, opts...)
			var s GetCheckDataEngineImageCanBeRollbackResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetCheckDataEngineImageCanBeRollbackResultOutput)
}

// A collection of arguments for invoking getCheckDataEngineImageCanBeRollback.
type GetCheckDataEngineImageCanBeRollbackOutputArgs struct {
	DataEngineId     pulumi.StringInput    `pulumi:"dataEngineId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetCheckDataEngineImageCanBeRollbackOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCheckDataEngineImageCanBeRollbackArgs)(nil)).Elem()
}

// A collection of values returned by getCheckDataEngineImageCanBeRollback.
type GetCheckDataEngineImageCanBeRollbackResultOutput struct{ *pulumi.OutputState }

func (GetCheckDataEngineImageCanBeRollbackResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCheckDataEngineImageCanBeRollbackResult)(nil)).Elem()
}

func (o GetCheckDataEngineImageCanBeRollbackResultOutput) ToGetCheckDataEngineImageCanBeRollbackResultOutput() GetCheckDataEngineImageCanBeRollbackResultOutput {
	return o
}

func (o GetCheckDataEngineImageCanBeRollbackResultOutput) ToGetCheckDataEngineImageCanBeRollbackResultOutputWithContext(ctx context.Context) GetCheckDataEngineImageCanBeRollbackResultOutput {
	return o
}

func (o GetCheckDataEngineImageCanBeRollbackResultOutput) DataEngineId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCheckDataEngineImageCanBeRollbackResult) string { return v.DataEngineId }).(pulumi.StringOutput)
}

func (o GetCheckDataEngineImageCanBeRollbackResultOutput) FromRecordId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCheckDataEngineImageCanBeRollbackResult) string { return v.FromRecordId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetCheckDataEngineImageCanBeRollbackResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCheckDataEngineImageCanBeRollbackResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCheckDataEngineImageCanBeRollbackResultOutput) IsRollback() pulumi.BoolOutput {
	return o.ApplyT(func(v GetCheckDataEngineImageCanBeRollbackResult) bool { return v.IsRollback }).(pulumi.BoolOutput)
}

func (o GetCheckDataEngineImageCanBeRollbackResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetCheckDataEngineImageCanBeRollbackResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetCheckDataEngineImageCanBeRollbackResultOutput) ToRecordId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCheckDataEngineImageCanBeRollbackResult) string { return v.ToRecordId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCheckDataEngineImageCanBeRollbackResultOutput{})
}
