// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dlc
{
    public static class GetCheckDataEngineImageCanBeRollback
    {
        public static Task<GetCheckDataEngineImageCanBeRollbackResult> InvokeAsync(GetCheckDataEngineImageCanBeRollbackArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCheckDataEngineImageCanBeRollbackResult>("tencentcloud:Dlc/getCheckDataEngineImageCanBeRollback:getCheckDataEngineImageCanBeRollback", args ?? new GetCheckDataEngineImageCanBeRollbackArgs(), options.WithDefaults());

        public static Output<GetCheckDataEngineImageCanBeRollbackResult> Invoke(GetCheckDataEngineImageCanBeRollbackInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCheckDataEngineImageCanBeRollbackResult>("tencentcloud:Dlc/getCheckDataEngineImageCanBeRollback:getCheckDataEngineImageCanBeRollback", args ?? new GetCheckDataEngineImageCanBeRollbackInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCheckDataEngineImageCanBeRollbackArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataEngineId", required: true)]
        public string DataEngineId { get; set; } = null!;

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetCheckDataEngineImageCanBeRollbackArgs()
        {
        }
        public static new GetCheckDataEngineImageCanBeRollbackArgs Empty => new GetCheckDataEngineImageCanBeRollbackArgs();
    }

    public sealed class GetCheckDataEngineImageCanBeRollbackInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("dataEngineId", required: true)]
        public Input<string> DataEngineId { get; set; } = null!;

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetCheckDataEngineImageCanBeRollbackInvokeArgs()
        {
        }
        public static new GetCheckDataEngineImageCanBeRollbackInvokeArgs Empty => new GetCheckDataEngineImageCanBeRollbackInvokeArgs();
    }


    [OutputType]
    public sealed class GetCheckDataEngineImageCanBeRollbackResult
    {
        public readonly string DataEngineId;
        public readonly string FromRecordId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsRollback;
        public readonly string? ResultOutputFile;
        public readonly string ToRecordId;

        [OutputConstructor]
        private GetCheckDataEngineImageCanBeRollbackResult(
            string dataEngineId,

            string fromRecordId,

            string id,

            bool isRollback,

            string? resultOutputFile,

            string toRecordId)
        {
            DataEngineId = dataEngineId;
            FromRecordId = fromRecordId;
            Id = id;
            IsRollback = isRollback;
            ResultOutputFile = resultOutputFile;
            ToRecordId = toRecordId;
        }
    }
}
