// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Gaap.Outputs
{

    [OutputType]
    public sealed class GetDomainErrorPageInfosErrorPageSetResult
    {
        public readonly string Body;
        public readonly ImmutableArray<string> ClearHeaders;
        public readonly string Domain;
        public readonly ImmutableArray<int> ErrorNos;
        public readonly string ErrorPageId;
        public readonly string ListenerId;
        public readonly int NewErrorNo;
        public readonly ImmutableArray<Outputs.GetDomainErrorPageInfosErrorPageSetSetHeaderResult> SetHeaders;
        public readonly int Status;

        [OutputConstructor]
        private GetDomainErrorPageInfosErrorPageSetResult(
            string body,

            ImmutableArray<string> clearHeaders,

            string domain,

            ImmutableArray<int> errorNos,

            string errorPageId,

            string listenerId,

            int newErrorNo,

            ImmutableArray<Outputs.GetDomainErrorPageInfosErrorPageSetSetHeaderResult> setHeaders,

            int status)
        {
            Body = body;
            ClearHeaders = clearHeaders;
            Domain = domain;
            ErrorNos = errorNos;
            ErrorPageId = errorPageId;
            ListenerId = listenerId;
            NewErrorNo = newErrorNo;
            SetHeaders = setHeaders;
            Status = status;
        }
    }
}
