// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Gaap.Outputs
{

    [OutputType]
    public sealed class GetGroupAndStatisticsProxyGroupSetProxySetResult
    {
        public readonly ImmutableArray<Outputs.GetGroupAndStatisticsProxyGroupSetProxySetListenerListResult> ListenerLists;
        public readonly string ProxyId;
        public readonly string ProxyName;

        [OutputConstructor]
        private GetGroupAndStatisticsProxyGroupSetProxySetResult(
            ImmutableArray<Outputs.GetGroupAndStatisticsProxyGroupSetProxySetListenerListResult> listenerLists,

            string proxyId,

            string proxyName)
        {
            ListenerLists = listenerLists;
            ProxyId = proxyId;
            ProxyName = proxyName;
        }
    }
}
