// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Gaap.Outputs
{

    [OutputType]
    public sealed class GetRuleRealServersBindRealServerSetResult
    {
        public readonly ImmutableArray<string> DownIpLists;
        public readonly string RealServerFailoverRole;
        public readonly string RealServerId;
        public readonly string RealServerIp;
        public readonly int RealServerPort;
        public readonly int RealServerStatus;
        public readonly int RealServerWeight;

        [OutputConstructor]
        private GetRuleRealServersBindRealServerSetResult(
            ImmutableArray<string> downIpLists,

            string realServerFailoverRole,

            string realServerId,

            string realServerIp,

            int realServerPort,

            int realServerStatus,

            int realServerWeight)
        {
            DownIpLists = downIpLists;
            RealServerFailoverRole = realServerFailoverRole;
            RealServerId = realServerId;
            RealServerIp = realServerIp;
            RealServerPort = realServerPort;
            RealServerStatus = realServerStatus;
            RealServerWeight = realServerWeight;
        }
    }
}
