// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tse.Outputs
{

    [OutputType]
    public sealed class CngwGatewayInstancePort
    {
        public readonly string? HttpPort;
        public readonly string? HttpsPort;
        public readonly string? TcpPort;
        public readonly string? UdpPort;

        [OutputConstructor]
        private CngwGatewayInstancePort(
            string? httpPort,

            string? httpsPort,

            string? tcpPort,

            string? udpPort)
        {
            HttpPort = httpPort;
            HttpsPort = httpsPort;
            TcpPort = tcpPort;
            UdpPort = udpPort;
        }
    }
}
