// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dlc.Inputs
{

    public sealed class UserDataEngineConfigSessionResourceTemplateGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("driverSize")]
        public Input<string>? DriverSize { get; set; }

        [Input("executorMaxNumbers")]
        public Input<int>? ExecutorMaxNumbers { get; set; }

        [Input("executorNums")]
        public Input<int>? ExecutorNums { get; set; }

        [Input("executorSize")]
        public Input<string>? ExecutorSize { get; set; }

        public UserDataEngineConfigSessionResourceTemplateGetArgs()
        {
        }
        public static new UserDataEngineConfigSessionResourceTemplateGetArgs Empty => new UserDataEngineConfigSessionResourceTemplateGetArgs();
    }
}
