// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cdwdoris.Inputs
{

    public sealed class InstanceUserMultiZoneInfosGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("subnetId")]
        public Input<string>? SubnetId { get; set; }

        [Input("subnetIpNum")]
        public Input<int>? SubnetIpNum { get; set; }

        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public InstanceUserMultiZoneInfosGetArgs()
        {
        }
        public static new InstanceUserMultiZoneInfosGetArgs Empty => new InstanceUserMultiZoneInfosGetArgs();
    }
}
