// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Thpc.Outputs
{

    [OutputType]
    public sealed class WorkspacesSystemDisk
    {
        public readonly string? DiskId;
        public readonly int? DiskSize;
        public readonly string? DiskType;

        [OutputConstructor]
        private WorkspacesSystemDisk(
            string? diskId,

            int? diskSize,

            string? diskType)
        {
            DiskId = diskId;
            DiskSize = diskSize;
            DiskType = diskType;
        }
    }
}
