// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package monitor

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetTmpInstances(ctx *pulumi.Context, args *GetTmpInstancesArgs, opts ...pulumi.InvokeOption) (*GetTmpInstancesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTmpInstancesResult
	err := ctx.Invoke("tencentcloud:Monitor/getTmpInstances:getTmpInstances", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTmpInstances.
type GetTmpInstancesArgs struct {
	InstanceChargeType *int                       `pulumi:"instanceChargeType"`
	InstanceIds        []string                   `pulumi:"instanceIds"`
	InstanceName       *string                    `pulumi:"instanceName"`
	InstanceStatuses   []int                      `pulumi:"instanceStatuses"`
	Ipv4Addresses      []string                   `pulumi:"ipv4Addresses"`
	ResultOutputFile   *string                    `pulumi:"resultOutputFile"`
	TagFilters         []GetTmpInstancesTagFilter `pulumi:"tagFilters"`
	Zones              []string                   `pulumi:"zones"`
}

// A collection of values returned by getTmpInstances.
type GetTmpInstancesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                 string                       `pulumi:"id"`
	InstanceChargeType *int                         `pulumi:"instanceChargeType"`
	InstanceIds        []string                     `pulumi:"instanceIds"`
	InstanceName       *string                      `pulumi:"instanceName"`
	InstanceSets       []GetTmpInstancesInstanceSet `pulumi:"instanceSets"`
	InstanceStatuses   []int                        `pulumi:"instanceStatuses"`
	Ipv4Addresses      []string                     `pulumi:"ipv4Addresses"`
	ResultOutputFile   *string                      `pulumi:"resultOutputFile"`
	TagFilters         []GetTmpInstancesTagFilter   `pulumi:"tagFilters"`
	Zones              []string                     `pulumi:"zones"`
}

func GetTmpInstancesOutput(ctx *pulumi.Context, args GetTmpInstancesOutputArgs, opts ...pulumi.InvokeOption) GetTmpInstancesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetTmpInstancesResult, error) {
			args := v.(GetTmpInstancesArgs)
			r, err := GetTmpInstances(ctx, &args, opts...)
			var s GetTmpInstancesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetTmpInstancesResultOutput)
}

// A collection of arguments for invoking getTmpInstances.
type GetTmpInstancesOutputArgs struct {
	InstanceChargeType pulumi.IntPtrInput                 `pulumi:"instanceChargeType"`
	InstanceIds        pulumi.StringArrayInput            `pulumi:"instanceIds"`
	InstanceName       pulumi.StringPtrInput              `pulumi:"instanceName"`
	InstanceStatuses   pulumi.IntArrayInput               `pulumi:"instanceStatuses"`
	Ipv4Addresses      pulumi.StringArrayInput            `pulumi:"ipv4Addresses"`
	ResultOutputFile   pulumi.StringPtrInput              `pulumi:"resultOutputFile"`
	TagFilters         GetTmpInstancesTagFilterArrayInput `pulumi:"tagFilters"`
	Zones              pulumi.StringArrayInput            `pulumi:"zones"`
}

func (GetTmpInstancesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTmpInstancesArgs)(nil)).Elem()
}

// A collection of values returned by getTmpInstances.
type GetTmpInstancesResultOutput struct{ *pulumi.OutputState }

func (GetTmpInstancesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTmpInstancesResult)(nil)).Elem()
}

func (o GetTmpInstancesResultOutput) ToGetTmpInstancesResultOutput() GetTmpInstancesResultOutput {
	return o
}

func (o GetTmpInstancesResultOutput) ToGetTmpInstancesResultOutputWithContext(ctx context.Context) GetTmpInstancesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetTmpInstancesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTmpInstancesResultOutput) InstanceChargeType() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) *int { return v.InstanceChargeType }).(pulumi.IntPtrOutput)
}

func (o GetTmpInstancesResultOutput) InstanceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) []string { return v.InstanceIds }).(pulumi.StringArrayOutput)
}

func (o GetTmpInstancesResultOutput) InstanceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) *string { return v.InstanceName }).(pulumi.StringPtrOutput)
}

func (o GetTmpInstancesResultOutput) InstanceSets() GetTmpInstancesInstanceSetArrayOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) []GetTmpInstancesInstanceSet { return v.InstanceSets }).(GetTmpInstancesInstanceSetArrayOutput)
}

func (o GetTmpInstancesResultOutput) InstanceStatuses() pulumi.IntArrayOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) []int { return v.InstanceStatuses }).(pulumi.IntArrayOutput)
}

func (o GetTmpInstancesResultOutput) Ipv4Addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) []string { return v.Ipv4Addresses }).(pulumi.StringArrayOutput)
}

func (o GetTmpInstancesResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetTmpInstancesResultOutput) TagFilters() GetTmpInstancesTagFilterArrayOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) []GetTmpInstancesTagFilter { return v.TagFilters }).(GetTmpInstancesTagFilterArrayOutput)
}

func (o GetTmpInstancesResultOutput) Zones() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTmpInstancesResult) []string { return v.Zones }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTmpInstancesResultOutput{})
}
