// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Monitor.Outputs
{

    [OutputType]
    public sealed class GetAlarmPolicyPolicyConditionsTempResult
    {
        public readonly ImmutableArray<Outputs.GetAlarmPolicyPolicyConditionsTempConditionResult> Conditions;
        public readonly ImmutableArray<Outputs.GetAlarmPolicyPolicyConditionsTempEventConditionResult> EventConditions;
        public readonly string TemplateName;

        [OutputConstructor]
        private GetAlarmPolicyPolicyConditionsTempResult(
            ImmutableArray<Outputs.GetAlarmPolicyPolicyConditionsTempConditionResult> conditions,

            ImmutableArray<Outputs.GetAlarmPolicyPolicyConditionsTempEventConditionResult> eventConditions,

            string templateName)
        {
            Conditions = conditions;
            EventConditions = eventConditions;
            TemplateName = templateName;
        }
    }
}
