// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Monitor.Outputs
{

    [OutputType]
    public sealed class GetAlarmAllNamespacesQceNamespacesNewsResult
    {
        public readonly ImmutableArray<string> AvailableRegions;
        public readonly string Config;
        public readonly string DashboardId;
        public readonly string Id;
        public readonly string Name;
        public readonly string ProductName;
        public readonly int SortId;
        public readonly string Value;

        [OutputConstructor]
        private GetAlarmAllNamespacesQceNamespacesNewsResult(
            ImmutableArray<string> availableRegions,

            string config,

            string dashboardId,

            string id,

            string name,

            string productName,

            int sortId,

            string value)
        {
            AvailableRegions = availableRegions;
            Config = config;
            DashboardId = dashboardId;
            Id = id;
            Name = name;
            ProductName = productName;
            SortId = sortId;
            Value = value;
        }
    }
}
