// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Monitor.Outputs
{

    [OutputType]
    public sealed class GetAlarmPolicyPolicyTagInstanceResult
    {
        public readonly int BindingStatus;
        public readonly int InstanceSum;
        public readonly string Key;
        public readonly int RegionId;
        public readonly string ServiceType;
        public readonly int TagStatus;
        public readonly string Value;

        [OutputConstructor]
        private GetAlarmPolicyPolicyTagInstanceResult(
            int bindingStatus,

            int instanceSum,

            string key,

            int regionId,

            string serviceType,

            int tagStatus,

            string value)
        {
            BindingStatus = bindingStatus;
            InstanceSum = instanceSum;
            Key = key;
            RegionId = regionId;
            ServiceType = serviceType;
            TagStatus = tagStatus;
            Value = value;
        }
    }
}
