// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Monitor.Outputs
{

    [OutputType]
    public sealed class GetAlarmMetricMetricMetricConfigResult
    {
        public readonly ImmutableArray<int> ContinuePeriods;
        public readonly ImmutableArray<string> Operators;
        public readonly ImmutableArray<int> Periods;

        [OutputConstructor]
        private GetAlarmMetricMetricMetricConfigResult(
            ImmutableArray<int> continuePeriods,

            ImmutableArray<string> operators,

            ImmutableArray<int> periods)
        {
            ContinuePeriods = continuePeriods;
            Operators = operators;
            Periods = periods;
        }
    }
}
