// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Monitor.Outputs
{

    [OutputType]
    public sealed class GetAlarmMetricMetricResult
    {
        public readonly string Description;
        public readonly ImmutableArray<string> Dimensions;
        public readonly int IsAdvanced;
        public readonly int IsOpen;
        public readonly double Max;
        public readonly ImmutableArray<Outputs.GetAlarmMetricMetricMetricConfigResult> MetricConfigs;
        public readonly string MetricName;
        public readonly double Min;
        public readonly string Namespace;
        public readonly ImmutableArray<Outputs.GetAlarmMetricMetricOperatorResult> Operators;
        public readonly ImmutableArray<int> Periods;
        public readonly int ProductId;
        public readonly string Unit;

        [OutputConstructor]
        private GetAlarmMetricMetricResult(
            string description,

            ImmutableArray<string> dimensions,

            int isAdvanced,

            int isOpen,

            double max,

            ImmutableArray<Outputs.GetAlarmMetricMetricMetricConfigResult> metricConfigs,

            string metricName,

            double min,

            string @namespace,

            ImmutableArray<Outputs.GetAlarmMetricMetricOperatorResult> operators,

            ImmutableArray<int> periods,

            int productId,

            string unit)
        {
            Description = description;
            Dimensions = dimensions;
            IsAdvanced = isAdvanced;
            IsOpen = isOpen;
            Max = max;
            MetricConfigs = metricConfigs;
            MetricName = metricName;
            Min = min;
            Namespace = @namespace;
            Operators = operators;
            Periods = periods;
            ProductId = productId;
            Unit = unit;
        }
    }
}
