// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Monitor
{
    public static class GetAlarmNoticeCallbacks
    {
        public static Task<GetAlarmNoticeCallbacksResult> InvokeAsync(GetAlarmNoticeCallbacksArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAlarmNoticeCallbacksResult>("tencentcloud:Monitor/getAlarmNoticeCallbacks:getAlarmNoticeCallbacks", args ?? new GetAlarmNoticeCallbacksArgs(), options.WithDefaults());

        public static Output<GetAlarmNoticeCallbacksResult> Invoke(GetAlarmNoticeCallbacksInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAlarmNoticeCallbacksResult>("tencentcloud:Monitor/getAlarmNoticeCallbacks:getAlarmNoticeCallbacks", args ?? new GetAlarmNoticeCallbacksInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAlarmNoticeCallbacksArgs : global::Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("tags")]
        private Dictionary<string, object>? _tags;
        public Dictionary<string, object> Tags
        {
            get => _tags ?? (_tags = new Dictionary<string, object>());
            set => _tags = value;
        }

        public GetAlarmNoticeCallbacksArgs()
        {
        }
        public static new GetAlarmNoticeCallbacksArgs Empty => new GetAlarmNoticeCallbacksArgs();
    }

    public sealed class GetAlarmNoticeCallbacksInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("tags")]
        private InputMap<object>? _tags;
        public InputMap<object> Tags
        {
            get => _tags ?? (_tags = new InputMap<object>());
            set => _tags = value;
        }

        public GetAlarmNoticeCallbacksInvokeArgs()
        {
        }
        public static new GetAlarmNoticeCallbacksInvokeArgs Empty => new GetAlarmNoticeCallbacksInvokeArgs();
    }


    [OutputType]
    public sealed class GetAlarmNoticeCallbacksResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? ResultOutputFile;
        public readonly ImmutableDictionary<string, object>? Tags;
        public readonly ImmutableArray<Outputs.GetAlarmNoticeCallbacksUrlNoticeResult> UrlNotices;

        [OutputConstructor]
        private GetAlarmNoticeCallbacksResult(
            string id,

            string? resultOutputFile,

            ImmutableDictionary<string, object>? tags,

            ImmutableArray<Outputs.GetAlarmNoticeCallbacksUrlNoticeResult> urlNotices)
        {
            Id = id;
            ResultOutputFile = resultOutputFile;
            Tags = tags;
            UrlNotices = urlNotices;
        }
    }
}
