// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Identity.Outputs
{

    [OutputType]
    public sealed class GetCenterUsersUserResult
    {
        public readonly string? CreateTime;
        public readonly string? Description;
        public readonly string? DisplayName;
        public readonly string? Email;
        public readonly string? FirstName;
        public readonly bool? IsSelected;
        public readonly string? LastName;
        public readonly string? UpdateTime;
        public readonly string? UserId;
        public readonly string? UserName;
        public readonly string? UserStatus;
        public readonly string? UserType;

        [OutputConstructor]
        private GetCenterUsersUserResult(
            string? createTime,

            string? description,

            string? displayName,

            string? email,

            string? firstName,

            bool? isSelected,

            string? lastName,

            string? updateTime,

            string? userId,

            string? userName,

            string? userStatus,

            string? userType)
        {
            CreateTime = createTime;
            Description = description;
            DisplayName = displayName;
            Email = email;
            FirstName = firstName;
            IsSelected = isSelected;
            LastName = lastName;
            UpdateTime = updateTime;
            UserId = userId;
            UserName = userName;
            UserStatus = userStatus;
            UserType = userType;
        }
    }
}
