// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.As.Outputs
{

    [OutputType]
    public sealed class LifecycleHookLifecycleCommand
    {
        public readonly string CommandId;
        public readonly string? Parameters;

        [OutputConstructor]
        private LifecycleHookLifecycleCommand(
            string commandId,

            string? parameters)
        {
            CommandId = commandId;
            Parameters = parameters;
        }
    }
}
