// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dnspod.Outputs
{

    [OutputType]
    public sealed class GetDomainListTagResult
    {
        public readonly string TagKey;
        public readonly ImmutableArray<string> TagValues;

        [OutputConstructor]
        private GetDomainListTagResult(
            string tagKey,

            ImmutableArray<string> tagValues)
        {
            TagKey = tagKey;
            TagValues = tagValues;
        }
    }
}
