// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Antiddos
{
    public static class GetListListener
    {
        public static Task<GetListListenerResult> InvokeAsync(GetListListenerArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetListListenerResult>("tencentcloud:Antiddos/getListListener:getListListener", args ?? new GetListListenerArgs(), options.WithDefaults());

        public static Output<GetListListenerResult> Invoke(GetListListenerInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetListListenerResult>("tencentcloud:Antiddos/getListListener:getListListener", args ?? new GetListListenerInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetListListenerArgs : global::Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetListListenerArgs()
        {
        }
        public static new GetListListenerArgs Empty => new GetListListenerArgs();
    }

    public sealed class GetListListenerInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetListListenerInvokeArgs()
        {
        }
        public static new GetListListenerInvokeArgs Empty => new GetListListenerInvokeArgs();
    }


    [OutputType]
    public sealed class GetListListenerResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetListListenerLayer4ListenerResult> Layer4Listeners;
        public readonly ImmutableArray<Outputs.GetListListenerLayer7ListenerResult> Layer7Listeners;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetListListenerResult(
            string id,

            ImmutableArray<Outputs.GetListListenerLayer4ListenerResult> layer4Listeners,

            ImmutableArray<Outputs.GetListListenerLayer7ListenerResult> layer7Listeners,

            string? resultOutputFile)
        {
            Id = id;
            Layer4Listeners = layer4Listeners;
            Layer7Listeners = layer7Listeners;
            ResultOutputFile = resultOutputFile;
        }
    }
}
