// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package antiddos

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetBgpBizTrend(ctx *pulumi.Context, args *GetBgpBizTrendArgs, opts ...pulumi.InvokeOption) (*GetBgpBizTrendResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetBgpBizTrendResult
	err := ctx.Invoke("tencentcloud:Antiddos/getBgpBizTrend:getBgpBizTrend", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBgpBizTrend.
type GetBgpBizTrendArgs struct {
	Business         string  `pulumi:"business"`
	EndTime          string  `pulumi:"endTime"`
	Flag             int     `pulumi:"flag"`
	InstanceId       string  `pulumi:"instanceId"`
	MetricName       string  `pulumi:"metricName"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	StartTime        string  `pulumi:"startTime"`
}

// A collection of values returned by getBgpBizTrend.
type GetBgpBizTrendResult struct {
	Business  string `pulumi:"business"`
	DataLists []int  `pulumi:"dataLists"`
	EndTime   string `pulumi:"endTime"`
	Flag      int    `pulumi:"flag"`
	// The provider-assigned unique ID for this managed resource.
	Id               string  `pulumi:"id"`
	InstanceId       string  `pulumi:"instanceId"`
	MaxData          int     `pulumi:"maxData"`
	MetricName       string  `pulumi:"metricName"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	StartTime        string  `pulumi:"startTime"`
	Total            int     `pulumi:"total"`
}

func GetBgpBizTrendOutput(ctx *pulumi.Context, args GetBgpBizTrendOutputArgs, opts ...pulumi.InvokeOption) GetBgpBizTrendResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetBgpBizTrendResult, error) {
			args := v.(GetBgpBizTrendArgs)
			r, err := GetBgpBizTrend(ctx, &args, opts...)
			var s GetBgpBizTrendResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetBgpBizTrendResultOutput)
}

// A collection of arguments for invoking getBgpBizTrend.
type GetBgpBizTrendOutputArgs struct {
	Business         pulumi.StringInput    `pulumi:"business"`
	EndTime          pulumi.StringInput    `pulumi:"endTime"`
	Flag             pulumi.IntInput       `pulumi:"flag"`
	InstanceId       pulumi.StringInput    `pulumi:"instanceId"`
	MetricName       pulumi.StringInput    `pulumi:"metricName"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
	StartTime        pulumi.StringInput    `pulumi:"startTime"`
}

func (GetBgpBizTrendOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBgpBizTrendArgs)(nil)).Elem()
}

// A collection of values returned by getBgpBizTrend.
type GetBgpBizTrendResultOutput struct{ *pulumi.OutputState }

func (GetBgpBizTrendResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBgpBizTrendResult)(nil)).Elem()
}

func (o GetBgpBizTrendResultOutput) ToGetBgpBizTrendResultOutput() GetBgpBizTrendResultOutput {
	return o
}

func (o GetBgpBizTrendResultOutput) ToGetBgpBizTrendResultOutputWithContext(ctx context.Context) GetBgpBizTrendResultOutput {
	return o
}

func (o GetBgpBizTrendResultOutput) Business() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) string { return v.Business }).(pulumi.StringOutput)
}

func (o GetBgpBizTrendResultOutput) DataLists() pulumi.IntArrayOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) []int { return v.DataLists }).(pulumi.IntArrayOutput)
}

func (o GetBgpBizTrendResultOutput) EndTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) string { return v.EndTime }).(pulumi.StringOutput)
}

func (o GetBgpBizTrendResultOutput) Flag() pulumi.IntOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) int { return v.Flag }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetBgpBizTrendResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetBgpBizTrendResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetBgpBizTrendResultOutput) MaxData() pulumi.IntOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) int { return v.MaxData }).(pulumi.IntOutput)
}

func (o GetBgpBizTrendResultOutput) MetricName() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) string { return v.MetricName }).(pulumi.StringOutput)
}

func (o GetBgpBizTrendResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetBgpBizTrendResultOutput) StartTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) string { return v.StartTime }).(pulumi.StringOutput)
}

func (o GetBgpBizTrendResultOutput) Total() pulumi.IntOutput {
	return o.ApplyT(func(v GetBgpBizTrendResult) int { return v.Total }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetBgpBizTrendResultOutput{})
}
