// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.PrivateDns.Outputs
{

    [OutputType]
    public sealed class GetEndPointsEndPointSetResult
    {
        public readonly string EndPointId;
        public readonly string EndPointName;
        public readonly string EndPointServiceId;
        public readonly ImmutableArray<string> EndPointVipSets;
        public readonly string RegionCode;
        public readonly ImmutableArray<Outputs.GetEndPointsEndPointSetTagResult> Tags;

        [OutputConstructor]
        private GetEndPointsEndPointSetResult(
            string endPointId,

            string endPointName,

            string endPointServiceId,

            ImmutableArray<string> endPointVipSets,

            string regionCode,

            ImmutableArray<Outputs.GetEndPointsEndPointSetTagResult> tags)
        {
            EndPointId = endPointId;
            EndPointName = endPointName;
            EndPointServiceId = endPointServiceId;
            EndPointVipSets = endPointVipSets;
            RegionCode = regionCode;
            Tags = tags;
        }
    }
}
