// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getProxyDetail(args: GetProxyDetailArgs, opts?: pulumi.InvokeOptions): Promise<GetProxyDetailResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Gaap/getProxyDetail:getProxyDetail", {
        "proxyId": args.proxyId,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getProxyDetail.
 */
export interface GetProxyDetailArgs {
    proxyId: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getProxyDetail.
 */
export interface GetProxyDetailResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly proxyDetails: outputs.Gaap.GetProxyDetailProxyDetail[];
    readonly proxyId: string;
    readonly resultOutputFile?: string;
}
export function getProxyDetailOutput(args: GetProxyDetailOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetProxyDetailResult> {
    return pulumi.output(args).apply((a: any) => getProxyDetail(a, opts))
}

/**
 * A collection of arguments for invoking getProxyDetail.
 */
export interface GetProxyDetailOutputArgs {
    proxyId: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
