// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getRegionAndPrice(args?: GetRegionAndPriceArgs, opts?: pulumi.InvokeOptions): Promise<GetRegionAndPriceResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Gaap/getRegionAndPrice:getRegionAndPrice", {
        "ipAddressVersion": args.ipAddressVersion,
        "packageType": args.packageType,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getRegionAndPrice.
 */
export interface GetRegionAndPriceArgs {
    ipAddressVersion?: string;
    packageType?: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getRegionAndPrice.
 */
export interface GetRegionAndPriceResult {
    readonly bandwidthUnitPrices: outputs.Gaap.GetRegionAndPriceBandwidthUnitPrice[];
    readonly currency: string;
    readonly destRegionSets: outputs.Gaap.GetRegionAndPriceDestRegionSet[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddressVersion?: string;
    readonly packageType?: string;
    readonly resultOutputFile?: string;
}
export function getRegionAndPriceOutput(args?: GetRegionAndPriceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRegionAndPriceResult> {
    return pulumi.output(args).apply((a: any) => getRegionAndPrice(a, opts))
}

/**
 * A collection of arguments for invoking getRegionAndPrice.
 */
export interface GetRegionAndPriceOutputArgs {
    ipAddressVersion?: pulumi.Input<string>;
    packageType?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
