// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getRuleRealServers(args: GetRuleRealServersArgs, opts?: pulumi.InvokeOptions): Promise<GetRuleRealServersResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Gaap/getRuleRealServers:getRuleRealServers", {
        "resultOutputFile": args.resultOutputFile,
        "ruleId": args.ruleId,
    }, opts);
}

/**
 * A collection of arguments for invoking getRuleRealServers.
 */
export interface GetRuleRealServersArgs {
    resultOutputFile?: string;
    ruleId: string;
}

/**
 * A collection of values returned by getRuleRealServers.
 */
export interface GetRuleRealServersResult {
    readonly bindRealServerSets: outputs.Gaap.GetRuleRealServersBindRealServerSet[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly realServerSets: outputs.Gaap.GetRuleRealServersRealServerSet[];
    readonly resultOutputFile?: string;
    readonly ruleId: string;
}
export function getRuleRealServersOutput(args: GetRuleRealServersOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRuleRealServersResult> {
    return pulumi.output(args).apply((a: any) => getRuleRealServers(a, opts))
}

/**
 * A collection of arguments for invoking getRuleRealServers.
 */
export interface GetRuleRealServersOutputArgs {
    resultOutputFile?: pulumi.Input<string>;
    ruleId: pulumi.Input<string>;
}
