// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticsearch

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetViews(ctx *pulumi.Context, args *GetViewsArgs, opts ...pulumi.InvokeOption) (*GetViewsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetViewsResult
	err := ctx.Invoke("tencentcloud:Elasticsearch/getViews:getViews", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getViews.
type GetViewsArgs struct {
	InstanceId       string  `pulumi:"instanceId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getViews.
type GetViewsResult struct {
	ClusterViews []GetViewsClusterView `pulumi:"clusterViews"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                `pulumi:"id"`
	InstanceId       string                `pulumi:"instanceId"`
	KibanasViews     []GetViewsKibanasView `pulumi:"kibanasViews"`
	NodesViews       []GetViewsNodesView   `pulumi:"nodesViews"`
	ResultOutputFile *string               `pulumi:"resultOutputFile"`
}

func GetViewsOutput(ctx *pulumi.Context, args GetViewsOutputArgs, opts ...pulumi.InvokeOption) GetViewsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetViewsResult, error) {
			args := v.(GetViewsArgs)
			r, err := GetViews(ctx, &args, opts...)
			var s GetViewsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetViewsResultOutput)
}

// A collection of arguments for invoking getViews.
type GetViewsOutputArgs struct {
	InstanceId       pulumi.StringInput    `pulumi:"instanceId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetViewsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetViewsArgs)(nil)).Elem()
}

// A collection of values returned by getViews.
type GetViewsResultOutput struct{ *pulumi.OutputState }

func (GetViewsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetViewsResult)(nil)).Elem()
}

func (o GetViewsResultOutput) ToGetViewsResultOutput() GetViewsResultOutput {
	return o
}

func (o GetViewsResultOutput) ToGetViewsResultOutputWithContext(ctx context.Context) GetViewsResultOutput {
	return o
}

func (o GetViewsResultOutput) ClusterViews() GetViewsClusterViewArrayOutput {
	return o.ApplyT(func(v GetViewsResult) []GetViewsClusterView { return v.ClusterViews }).(GetViewsClusterViewArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetViewsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetViewsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetViewsResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetViewsResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetViewsResultOutput) KibanasViews() GetViewsKibanasViewArrayOutput {
	return o.ApplyT(func(v GetViewsResult) []GetViewsKibanasView { return v.KibanasViews }).(GetViewsKibanasViewArrayOutput)
}

func (o GetViewsResultOutput) NodesViews() GetViewsNodesViewArrayOutput {
	return o.ApplyT(func(v GetViewsResult) []GetViewsNodesView { return v.NodesViews }).(GetViewsNodesViewArrayOutput)
}

func (o GetViewsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetViewsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetViewsResultOutput{})
}
