// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Csip.Inputs
{

    public sealed class RiskCenterTaskAdvanceCfgPortRiskArgs : global::Pulumi.ResourceArgs
    {
        [Input("checkType", required: true)]
        public Input<int> CheckType { get; set; } = null!;

        [Input("detail", required: true)]
        public Input<string> Detail { get; set; } = null!;

        [Input("enable", required: true)]
        public Input<int> Enable { get; set; } = null!;

        [Input("portSets", required: true)]
        public Input<string> PortSets { get; set; } = null!;

        public RiskCenterTaskAdvanceCfgPortRiskArgs()
        {
        }
        public static new RiskCenterTaskAdvanceCfgPortRiskArgs Empty => new RiskCenterTaskAdvanceCfgPortRiskArgs();
    }
}
