// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getOverviewDdosEventList(args: GetOverviewDdosEventListArgs, opts?: pulumi.InvokeOptions): Promise<GetOverviewDdosEventListResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Antiddos/getOverviewDdosEventList:getOverviewDdosEventList", {
        "attackStatus": args.attackStatus,
        "endTime": args.endTime,
        "resultOutputFile": args.resultOutputFile,
        "startTime": args.startTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getOverviewDdosEventList.
 */
export interface GetOverviewDdosEventListArgs {
    attackStatus?: string;
    endTime: string;
    resultOutputFile?: string;
    startTime: string;
}

/**
 * A collection of values returned by getOverviewDdosEventList.
 */
export interface GetOverviewDdosEventListResult {
    readonly attackStatus?: string;
    readonly endTime: string;
    readonly eventLists: outputs.Antiddos.GetOverviewDdosEventListEventList[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly resultOutputFile?: string;
    readonly startTime: string;
}
export function getOverviewDdosEventListOutput(args: GetOverviewDdosEventListOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOverviewDdosEventListResult> {
    return pulumi.output(args).apply((a: any) => getOverviewDdosEventList(a, opts))
}

/**
 * A collection of arguments for invoking getOverviewDdosEventList.
 */
export interface GetOverviewDdosEventListOutputArgs {
    attackStatus?: pulumi.Input<string>;
    endTime: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
    startTime: pulumi.Input<string>;
}
