// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Antiddos.Inputs
{

    public sealed class PacketFilterConfigPacketFilterConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        [Input("depth")]
        public Input<int>? Depth { get; set; }

        [Input("depth2")]
        public Input<int>? Depth2 { get; set; }

        [Input("dportEnd", required: true)]
        public Input<int> DportEnd { get; set; } = null!;

        [Input("dportStart", required: true)]
        public Input<int> DportStart { get; set; } = null!;

        [Input("isNot")]
        public Input<int>? IsNot { get; set; }

        [Input("isNot2")]
        public Input<int>? IsNot2 { get; set; }

        [Input("matchBegin")]
        public Input<string>? MatchBegin { get; set; }

        [Input("matchBegin2")]
        public Input<string>? MatchBegin2 { get; set; }

        [Input("matchLogic")]
        public Input<string>? MatchLogic { get; set; }

        [Input("matchType")]
        public Input<string>? MatchType { get; set; }

        [Input("matchType2")]
        public Input<string>? MatchType2 { get; set; }

        [Input("offset")]
        public Input<int>? Offset { get; set; }

        [Input("offset2")]
        public Input<int>? Offset2 { get; set; }

        [Input("pktLenGt")]
        public Input<int>? PktLenGt { get; set; }

        [Input("pktlenMax", required: true)]
        public Input<int> PktlenMax { get; set; } = null!;

        [Input("pktlenMin", required: true)]
        public Input<int> PktlenMin { get; set; } = null!;

        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        [Input("sportEnd", required: true)]
        public Input<int> SportEnd { get; set; } = null!;

        [Input("sportStart", required: true)]
        public Input<int> SportStart { get; set; } = null!;

        [Input("str")]
        public Input<string>? Str { get; set; }

        [Input("str2")]
        public Input<string>? Str2 { get; set; }

        public PacketFilterConfigPacketFilterConfigGetArgs()
        {
        }
        public static new PacketFilterConfigPacketFilterConfigGetArgs Empty => new PacketFilterConfigPacketFilterConfigGetArgs();
    }
}
