// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getWhiteBoxDeviceFingerprints(args: GetWhiteBoxDeviceFingerprintsArgs, opts?: pulumi.InvokeOptions): Promise<GetWhiteBoxDeviceFingerprintsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Kms/getWhiteBoxDeviceFingerprints:getWhiteBoxDeviceFingerprints", {
        "keyId": args.keyId,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getWhiteBoxDeviceFingerprints.
 */
export interface GetWhiteBoxDeviceFingerprintsArgs {
    keyId: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getWhiteBoxDeviceFingerprints.
 */
export interface GetWhiteBoxDeviceFingerprintsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keyId: string;
    readonly lists: outputs.Kms.GetWhiteBoxDeviceFingerprintsList[];
    readonly resultOutputFile?: string;
}
export function getWhiteBoxDeviceFingerprintsOutput(args: GetWhiteBoxDeviceFingerprintsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetWhiteBoxDeviceFingerprintsResult> {
    return pulumi.output(args).apply((a: any) => getWhiteBoxDeviceFingerprints(a, opts))
}

/**
 * A collection of arguments for invoking getWhiteBoxDeviceFingerprints.
 */
export interface GetWhiteBoxDeviceFingerprintsOutputArgs {
    keyId: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
