// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getDescribeDataEngineImageVersions(args: GetDescribeDataEngineImageVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetDescribeDataEngineImageVersionsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Dlc/getDescribeDataEngineImageVersions:getDescribeDataEngineImageVersions", {
        "engineType": args.engineType,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getDescribeDataEngineImageVersions.
 */
export interface GetDescribeDataEngineImageVersionsArgs {
    engineType: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getDescribeDataEngineImageVersions.
 */
export interface GetDescribeDataEngineImageVersionsResult {
    readonly engineType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly imageParentVersions: outputs.Dlc.GetDescribeDataEngineImageVersionsImageParentVersion[];
    readonly resultOutputFile?: string;
}
export function getDescribeDataEngineImageVersionsOutput(args: GetDescribeDataEngineImageVersionsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDescribeDataEngineImageVersionsResult> {
    return pulumi.output(args).apply((a: any) => getDescribeDataEngineImageVersions(a, opts))
}

/**
 * A collection of arguments for invoking getDescribeDataEngineImageVersions.
 */
export interface GetDescribeDataEngineImageVersionsOutputArgs {
    engineType: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
