// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getDescribeWorkGroupInfo(args?: GetDescribeWorkGroupInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetDescribeWorkGroupInfoResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Dlc/getDescribeWorkGroupInfo:getDescribeWorkGroupInfo", {
        "filters": args.filters,
        "resultOutputFile": args.resultOutputFile,
        "sortBy": args.sortBy,
        "sorting": args.sorting,
        "type": args.type,
        "workGroupId": args.workGroupId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDescribeWorkGroupInfo.
 */
export interface GetDescribeWorkGroupInfoArgs {
    filters?: inputs.Dlc.GetDescribeWorkGroupInfoFilter[];
    resultOutputFile?: string;
    sortBy?: string;
    sorting?: string;
    type?: string;
    workGroupId?: number;
}

/**
 * A collection of values returned by getDescribeWorkGroupInfo.
 */
export interface GetDescribeWorkGroupInfoResult {
    readonly filters?: outputs.Dlc.GetDescribeWorkGroupInfoFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly resultOutputFile?: string;
    readonly sortBy?: string;
    readonly sorting?: string;
    readonly type?: string;
    readonly workGroupId?: number;
    readonly workGroupInfos: outputs.Dlc.GetDescribeWorkGroupInfoWorkGroupInfo[];
}
export function getDescribeWorkGroupInfoOutput(args?: GetDescribeWorkGroupInfoOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDescribeWorkGroupInfoResult> {
    return pulumi.output(args).apply((a: any) => getDescribeWorkGroupInfo(a, opts))
}

/**
 * A collection of arguments for invoking getDescribeWorkGroupInfo.
 */
export interface GetDescribeWorkGroupInfoOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.Dlc.GetDescribeWorkGroupInfoFilterArgs>[]>;
    resultOutputFile?: pulumi.Input<string>;
    sortBy?: pulumi.Input<string>;
    sorting?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    workGroupId?: pulumi.Input<number>;
}
