// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Ssl.Inputs
{

    public sealed class UpdateCertificateInstanceOperationResourceTypesRegionArgs : global::Pulumi.ResourceArgs
    {
        [Input("regions")]
        private InputList<string>? _regions;
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        [Input("resourceType")]
        public Input<string>? ResourceType { get; set; }

        public UpdateCertificateInstanceOperationResourceTypesRegionArgs()
        {
        }
        public static new UpdateCertificateInstanceOperationResourceTypesRegionArgs Empty => new UpdateCertificateInstanceOperationResourceTypesRegionArgs();
    }
}
