// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cvm
{
    [TencentcloudResourceType("tencentcloud:Cvm/actionTimer:ActionTimer")]
    public partial class ActionTimer : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Scheduled tasks. This parameter can be used to specify scheduled tasks for instances, and currently only supports
        /// scheduled destruction.
        /// </summary>
        [Output("actionTimer")]
        public Output<Outputs.ActionTimerActionTimer> CvmActionTimer { get; private set; } = null!;

        /// <summary>
        /// Instance ID.
        /// </summary>
        [Output("instanceId")]
        public Output<string> InstanceId { get; private set; } = null!;


        /// <summary>
        /// Create a ActionTimer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ActionTimer(string name, ActionTimerArgs args, CustomResourceOptions? options = null)
            : base("tencentcloud:Cvm/actionTimer:ActionTimer", name, args ?? new ActionTimerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ActionTimer(string name, Input<string> id, ActionTimerState? state = null, CustomResourceOptions? options = null)
            : base("tencentcloud:Cvm/actionTimer:ActionTimer", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/matrixorigin",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ActionTimer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ActionTimer Get(string name, Input<string> id, ActionTimerState? state = null, CustomResourceOptions? options = null)
        {
            return new ActionTimer(name, id, state, options);
        }
    }

    public sealed class ActionTimerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Scheduled tasks. This parameter can be used to specify scheduled tasks for instances, and currently only supports
        /// scheduled destruction.
        /// </summary>
        [Input("actionTimer", required: true)]
        public Input<Inputs.ActionTimerActionTimerArgs> CvmActionTimer { get; set; } = null!;

        /// <summary>
        /// Instance ID.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        public ActionTimerArgs()
        {
        }
        public static new ActionTimerArgs Empty => new ActionTimerArgs();
    }

    public sealed class ActionTimerState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Scheduled tasks. This parameter can be used to specify scheduled tasks for instances, and currently only supports
        /// scheduled destruction.
        /// </summary>
        [Input("actionTimer")]
        public Input<Inputs.ActionTimerActionTimerGetArgs>? CvmActionTimer { get; set; }

        /// <summary>
        /// Instance ID.
        /// </summary>
        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        public ActionTimerState()
        {
        }
        public static new ActionTimerState Empty => new ActionTimerState();
    }
}
