// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cdwpg.Inputs
{

    public sealed class InstanceResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("count", required: true)]
        public Input<int> Count { get; set; } = null!;

        [Input("diskSpec", required: true)]
        public Input<Inputs.InstanceResourceDiskSpecArgs> DiskSpec { get; set; } = null!;

        [Input("specName", required: true)]
        public Input<string> SpecName { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public InstanceResourceArgs()
        {
        }
        public static new InstanceResourceArgs Empty => new InstanceResourceArgs();
    }
}
