// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Waf.Outputs
{

    [OutputType]
    public sealed class GetAttackLogHistogramDataResult
    {
        public readonly int Count;
        public readonly int TimeStamp;

        [OutputConstructor]
        private GetAttackLogHistogramDataResult(
            int count,

            int timeStamp)
        {
            Count = count;
            TimeStamp = timeStamp;
        }
    }
}
