// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Clickhouse
{
    public static class GetInstanceNodes
    {
        public static Task<GetInstanceNodesResult> InvokeAsync(GetInstanceNodesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetInstanceNodesResult>("tencentcloud:Clickhouse/getInstanceNodes:getInstanceNodes", args ?? new GetInstanceNodesArgs(), options.WithDefaults());

        public static Output<GetInstanceNodesResult> Invoke(GetInstanceNodesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceNodesResult>("tencentcloud:Clickhouse/getInstanceNodes:getInstanceNodes", args ?? new GetInstanceNodesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetInstanceNodesArgs : global::Pulumi.InvokeArgs
    {
        [Input("displayPolicy")]
        public string? DisplayPolicy { get; set; }

        [Input("forceAll")]
        public bool? ForceAll { get; set; }

        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("nodeRole")]
        public string? NodeRole { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetInstanceNodesArgs()
        {
        }
        public static new GetInstanceNodesArgs Empty => new GetInstanceNodesArgs();
    }

    public sealed class GetInstanceNodesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("displayPolicy")]
        public Input<string>? DisplayPolicy { get; set; }

        [Input("forceAll")]
        public Input<bool>? ForceAll { get; set; }

        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("nodeRole")]
        public Input<string>? NodeRole { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetInstanceNodesInvokeArgs()
        {
        }
        public static new GetInstanceNodesInvokeArgs Empty => new GetInstanceNodesInvokeArgs();
    }


    [OutputType]
    public sealed class GetInstanceNodesResult
    {
        public readonly string? DisplayPolicy;
        public readonly bool? ForceAll;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly ImmutableArray<Outputs.GetInstanceNodesInstanceNodesListResult> InstanceNodesLists;
        public readonly string? NodeRole;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetInstanceNodesResult(
            string? displayPolicy,

            bool? forceAll,

            string id,

            string instanceId,

            ImmutableArray<Outputs.GetInstanceNodesInstanceNodesListResult> instanceNodesLists,

            string? nodeRole,

            string? resultOutputFile)
        {
            DisplayPolicy = displayPolicy;
            ForceAll = forceAll;
            Id = id;
            InstanceId = instanceId;
            InstanceNodesLists = instanceNodesLists;
            NodeRole = nodeRole;
            ResultOutputFile = resultOutputFile;
        }
    }
}
