// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Emr.Inputs
{

    public sealed class ClusterPreExecutedFileSettingArgs : global::Pulumi.ResourceArgs
    {
        [Input("args")]
        private InputList<string>? _args;
        public InputList<string> Args
        {
            get => _args ?? (_args = new InputList<string>());
            set => _args = value;
        }

        [Input("cosFileName")]
        public Input<string>? CosFileName { get; set; }

        [Input("cosFileUri")]
        public Input<string>? CosFileUri { get; set; }

        [Input("cosSecretId")]
        public Input<string>? CosSecretId { get; set; }

        [Input("cosSecretKey")]
        public Input<string>? CosSecretKey { get; set; }

        [Input("remark")]
        public Input<string>? Remark { get; set; }

        [Input("runOrder")]
        public Input<int>? RunOrder { get; set; }

        [Input("whenRun")]
        public Input<string>? WhenRun { get; set; }

        public ClusterPreExecutedFileSettingArgs()
        {
        }
        public static new ClusterPreExecutedFileSettingArgs Empty => new ClusterPreExecutedFileSettingArgs();
    }
}
