// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Emr.Inputs
{

    public sealed class ClusterTerminateNodeInfoArgs : global::Pulumi.ResourceArgs
    {
        [Input("cvmInstanceIds")]
        private InputList<string>? _cvmInstanceIds;
        public InputList<string> CvmInstanceIds
        {
            get => _cvmInstanceIds ?? (_cvmInstanceIds = new InputList<string>());
            set => _cvmInstanceIds = value;
        }

        [Input("nodeFlag")]
        public Input<string>? NodeFlag { get; set; }

        public ClusterTerminateNodeInfoArgs()
        {
        }
        public static new ClusterTerminateNodeInfoArgs Empty => new ClusterTerminateNodeInfoArgs();
    }
}
