// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Kubernetes.Inputs
{

    public sealed class ClusterMasterAttachmentMasterConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataDisk")]
        public Input<Inputs.ClusterMasterAttachmentMasterConfigDataDiskGetArgs>? DataDisk { get; set; }

        [Input("desiredPodNumber")]
        public Input<int>? DesiredPodNumber { get; set; }

        [Input("dockerGraphPath")]
        public Input<string>? DockerGraphPath { get; set; }

        [Input("extraArgs")]
        public Input<Inputs.ClusterMasterAttachmentMasterConfigExtraArgsGetArgs>? ExtraArgs { get; set; }

        [Input("gpuArgs")]
        public Input<Inputs.ClusterMasterAttachmentMasterConfigGpuArgsGetArgs>? GpuArgs { get; set; }

        [Input("labels")]
        private InputList<Inputs.ClusterMasterAttachmentMasterConfigLabelGetArgs>? _labels;
        public InputList<Inputs.ClusterMasterAttachmentMasterConfigLabelGetArgs> Labels
        {
            get => _labels ?? (_labels = new InputList<Inputs.ClusterMasterAttachmentMasterConfigLabelGetArgs>());
            set => _labels = value;
        }

        [Input("mountTarget")]
        public Input<string>? MountTarget { get; set; }

        [Input("taints")]
        private InputList<Inputs.ClusterMasterAttachmentMasterConfigTaintGetArgs>? _taints;
        public InputList<Inputs.ClusterMasterAttachmentMasterConfigTaintGetArgs> Taints
        {
            get => _taints ?? (_taints = new InputList<Inputs.ClusterMasterAttachmentMasterConfigTaintGetArgs>());
            set => _taints = value;
        }

        [Input("unschedulable")]
        public Input<int>? Unschedulable { get; set; }

        [Input("userScript")]
        public Input<string>? UserScript { get; set; }

        public ClusterMasterAttachmentMasterConfigGetArgs()
        {
        }
        public static new ClusterMasterAttachmentMasterConfigGetArgs Empty => new ClusterMasterAttachmentMasterConfigGetArgs();
    }
}
