// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Kubernetes.Inputs
{

    public sealed class ClusterMasterAttachmentMasterConfigExtraArgsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("kubelets")]
        private InputList<string>? _kubelets;
        public InputList<string> Kubelets
        {
            get => _kubelets ?? (_kubelets = new InputList<string>());
            set => _kubelets = value;
        }

        public ClusterMasterAttachmentMasterConfigExtraArgsGetArgs()
        {
        }
        public static new ClusterMasterAttachmentMasterConfigExtraArgsGetArgs Empty => new ClusterMasterAttachmentMasterConfigExtraArgsGetArgs();
    }
}
