// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cls.Inputs
{

    public sealed class TopicExtendsAnonymousAccessArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Inputs.TopicExtendsAnonymousAccessConditionArgs>? _conditions;
        public InputList<Inputs.TopicExtendsAnonymousAccessConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.TopicExtendsAnonymousAccessConditionArgs>());
            set => _conditions = value;
        }

        [Input("operations")]
        private InputList<string>? _operations;
        public InputList<string> Operations
        {
            get => _operations ?? (_operations = new InputList<string>());
            set => _operations = value;
        }

        public TopicExtendsAnonymousAccessArgs()
        {
        }
        public static new TopicExtendsAnonymousAccessArgs Empty => new TopicExtendsAnonymousAccessArgs();
    }
}
