// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Vod.Outputs
{

    [OutputType]
    public sealed class ProcedureTemplateMediaProcessTaskTranscodeTaskList
    {
        public readonly Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListCopyRightWatermark? CopyRightWatermark;
        public readonly string Definition;
        public readonly double? EndTimeOffset;
        public readonly ImmutableArray<Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListHeadTailList> HeadTailLists;
        public readonly ImmutableArray<Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListMosaicList> MosaicLists;
        public readonly double? StartTimeOffset;
        public readonly Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListTraceWatermark? TraceWatermark;
        public readonly ImmutableArray<Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListWatermarkList> WatermarkLists;

        [OutputConstructor]
        private ProcedureTemplateMediaProcessTaskTranscodeTaskList(
            Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListCopyRightWatermark? copyRightWatermark,

            string definition,

            double? endTimeOffset,

            ImmutableArray<Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListHeadTailList> headTailLists,

            ImmutableArray<Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListMosaicList> mosaicLists,

            double? startTimeOffset,

            Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListTraceWatermark? traceWatermark,

            ImmutableArray<Outputs.ProcedureTemplateMediaProcessTaskTranscodeTaskListWatermarkList> watermarkLists)
        {
            CopyRightWatermark = copyRightWatermark;
            Definition = definition;
            EndTimeOffset = endTimeOffset;
            HeadTailLists = headTailLists;
            MosaicLists = mosaicLists;
            StartTimeOffset = startTimeOffset;
            TraceWatermark = traceWatermark;
            WatermarkLists = watermarkLists;
        }
    }
}
