// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Clickhouse.Inputs
{

    public sealed class AccountPermissionDatabasePrivilegeListGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("databaseName", required: true)]
        public Input<string> DatabaseName { get; set; } = null!;

        [Input("databasePrivileges")]
        private InputList<string>? _databasePrivileges;
        public InputList<string> DatabasePrivileges
        {
            get => _databasePrivileges ?? (_databasePrivileges = new InputList<string>());
            set => _databasePrivileges = value;
        }

        [Input("tablePrivilegeLists")]
        private InputList<Inputs.AccountPermissionDatabasePrivilegeListTablePrivilegeListGetArgs>? _tablePrivilegeLists;
        public InputList<Inputs.AccountPermissionDatabasePrivilegeListTablePrivilegeListGetArgs> TablePrivilegeLists
        {
            get => _tablePrivilegeLists ?? (_tablePrivilegeLists = new InputList<Inputs.AccountPermissionDatabasePrivilegeListTablePrivilegeListGetArgs>());
            set => _tablePrivilegeLists = value;
        }

        public AccountPermissionDatabasePrivilegeListGetArgs()
        {
        }
        public static new AccountPermissionDatabasePrivilegeListGetArgs Empty => new AccountPermissionDatabasePrivilegeListGetArgs();
    }
}
