// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Elasticsearch
{
    public static class GetDescribeIndexList
    {
        public static Task<GetDescribeIndexListResult> InvokeAsync(GetDescribeIndexListArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDescribeIndexListResult>("tencentcloud:Elasticsearch/getDescribeIndexList:getDescribeIndexList", args ?? new GetDescribeIndexListArgs(), options.WithDefaults());

        public static Output<GetDescribeIndexListResult> Invoke(GetDescribeIndexListInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDescribeIndexListResult>("tencentcloud:Elasticsearch/getDescribeIndexList:getDescribeIndexList", args ?? new GetDescribeIndexListInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDescribeIndexListArgs : global::Pulumi.InvokeArgs
    {
        [Input("indexName")]
        public string? IndexName { get; set; }

        [Input("indexStatusLists")]
        private List<string>? _indexStatusLists;
        public List<string> IndexStatusLists
        {
            get => _indexStatusLists ?? (_indexStatusLists = new List<string>());
            set => _indexStatusLists = value;
        }

        [Input("indexType", required: true)]
        public string IndexType { get; set; } = null!;

        [Input("instanceId")]
        public string? InstanceId { get; set; }

        [Input("order")]
        public string? Order { get; set; }

        [Input("orderBy")]
        public string? OrderBy { get; set; }

        [Input("password")]
        public string? Password { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("username")]
        public string? Username { get; set; }

        public GetDescribeIndexListArgs()
        {
        }
        public static new GetDescribeIndexListArgs Empty => new GetDescribeIndexListArgs();
    }

    public sealed class GetDescribeIndexListInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("indexName")]
        public Input<string>? IndexName { get; set; }

        [Input("indexStatusLists")]
        private InputList<string>? _indexStatusLists;
        public InputList<string> IndexStatusLists
        {
            get => _indexStatusLists ?? (_indexStatusLists = new InputList<string>());
            set => _indexStatusLists = value;
        }

        [Input("indexType", required: true)]
        public Input<string> IndexType { get; set; } = null!;

        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        [Input("order")]
        public Input<string>? Order { get; set; }

        [Input("orderBy")]
        public Input<string>? OrderBy { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        public GetDescribeIndexListInvokeArgs()
        {
        }
        public static new GetDescribeIndexListInvokeArgs Empty => new GetDescribeIndexListInvokeArgs();
    }


    [OutputType]
    public sealed class GetDescribeIndexListResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetDescribeIndexListIndexMetaFieldResult> IndexMetaFields;
        public readonly string? IndexName;
        public readonly ImmutableArray<string> IndexStatusLists;
        public readonly string IndexType;
        public readonly string? InstanceId;
        public readonly string? Order;
        public readonly string? OrderBy;
        public readonly string? Password;
        public readonly string? ResultOutputFile;
        public readonly string? Username;

        [OutputConstructor]
        private GetDescribeIndexListResult(
            string id,

            ImmutableArray<Outputs.GetDescribeIndexListIndexMetaFieldResult> indexMetaFields,

            string? indexName,

            ImmutableArray<string> indexStatusLists,

            string indexType,

            string? instanceId,

            string? order,

            string? orderBy,

            string? password,

            string? resultOutputFile,

            string? username)
        {
            Id = id;
            IndexMetaFields = indexMetaFields;
            IndexName = indexName;
            IndexStatusLists = indexStatusLists;
            IndexType = indexType;
            InstanceId = instanceId;
            Order = order;
            OrderBy = orderBy;
            Password = password;
            ResultOutputFile = resultOutputFile;
            Username = username;
        }
    }
}
