// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.PrivateDns
{
    public static class GetForwardRules
    {
        public static Task<GetForwardRulesResult> InvokeAsync(GetForwardRulesArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetForwardRulesResult>("tencentcloud:PrivateDns/getForwardRules:getForwardRules", args ?? new GetForwardRulesArgs(), options.WithDefaults());

        public static Output<GetForwardRulesResult> Invoke(GetForwardRulesInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetForwardRulesResult>("tencentcloud:PrivateDns/getForwardRules:getForwardRules", args ?? new GetForwardRulesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetForwardRulesArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetForwardRulesFilterArgs>? _filters;
        public List<Inputs.GetForwardRulesFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetForwardRulesFilterArgs>());
            set => _filters = value;
        }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetForwardRulesArgs()
        {
        }
        public static new GetForwardRulesArgs Empty => new GetForwardRulesArgs();
    }

    public sealed class GetForwardRulesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private InputList<Inputs.GetForwardRulesFilterInputArgs>? _filters;
        public InputList<Inputs.GetForwardRulesFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetForwardRulesFilterInputArgs>());
            set => _filters = value;
        }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetForwardRulesInvokeArgs()
        {
        }
        public static new GetForwardRulesInvokeArgs Empty => new GetForwardRulesInvokeArgs();
    }


    [OutputType]
    public sealed class GetForwardRulesResult
    {
        public readonly ImmutableArray<Outputs.GetForwardRulesFilterResult> Filters;
        public readonly ImmutableArray<Outputs.GetForwardRulesForwardRuleSetResult> ForwardRuleSets;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetForwardRulesResult(
            ImmutableArray<Outputs.GetForwardRulesFilterResult> filters,

            ImmutableArray<Outputs.GetForwardRulesForwardRuleSetResult> forwardRuleSets,

            string id,

            string? resultOutputFile)
        {
            Filters = filters;
            ForwardRuleSets = forwardRuleSets;
            Id = id;
            ResultOutputFile = resultOutputFile;
        }
    }
}
