// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Ses.Outputs
{

    [OutputType]
    public sealed class GetSendTasksDataTemplateResult
    {
        public readonly string TemplateData;
        public readonly int TemplateId;

        [OutputConstructor]
        private GetSendTasksDataTemplateResult(
            string templateData,

            int templateId)
        {
            TemplateData = templateData;
            TemplateId = templateId;
        }
    }
}
