// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Postgresql.Outputs
{

    [OutputType]
    public sealed class AccountPrivilegesOperationModifyPrivilegeSetDatabasePrivilege
    {
        public readonly Outputs.AccountPrivilegesOperationModifyPrivilegeSetDatabasePrivilegeObject? Object;
        public readonly ImmutableArray<string> PrivilegeSets;

        [OutputConstructor]
        private AccountPrivilegesOperationModifyPrivilegeSetDatabasePrivilege(
            Outputs.AccountPrivilegesOperationModifyPrivilegeSetDatabasePrivilegeObject? @object,

            ImmutableArray<string> privilegeSets)
        {
            Object = @object;
            PrivilegeSets = privilegeSets;
        }
    }
}
