// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Postgresql.Outputs
{

    [OutputType]
    public sealed class CloneDbInstanceDbNodeSet
    {
        public readonly string? DedicatedClusterId;
        public readonly string Role;
        public readonly string Zone;

        [OutputConstructor]
        private CloneDbInstanceDbNodeSet(
            string? dedicatedClusterId,

            string role,

            string zone)
        {
            DedicatedClusterId = dedicatedClusterId;
            Role = role;
            Zone = zone;
        }
    }
}
