// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getHbaseInstances(args: GetHbaseInstancesArgs, opts?: pulumi.InvokeOptions): Promise<GetHbaseInstancesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Lite/getHbaseInstances:getHbaseInstances", {
        "asc": args.asc,
        "displayStrategy": args.displayStrategy,
        "filters": args.filters,
        "orderField": args.orderField,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getHbaseInstances.
 */
export interface GetHbaseInstancesArgs {
    asc?: number;
    displayStrategy: string;
    filters?: inputs.Lite.GetHbaseInstancesFilter[];
    orderField?: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getHbaseInstances.
 */
export interface GetHbaseInstancesResult {
    readonly asc?: number;
    readonly displayStrategy: string;
    readonly filters?: outputs.Lite.GetHbaseInstancesFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceLists: outputs.Lite.GetHbaseInstancesInstanceList[];
    readonly orderField?: string;
    readonly resultOutputFile?: string;
}
export function getHbaseInstancesOutput(args: GetHbaseInstancesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetHbaseInstancesResult> {
    return pulumi.output(args).apply((a: any) => getHbaseInstances(a, opts))
}

/**
 * A collection of arguments for invoking getHbaseInstances.
 */
export interface GetHbaseInstancesOutputArgs {
    asc?: pulumi.Input<number>;
    displayStrategy: pulumi.Input<string>;
    filters?: pulumi.Input<pulumi.Input<inputs.Lite.GetHbaseInstancesFilterArgs>[]>;
    orderField?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
