// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Ssm
{
    public static class GetRotationDetail
    {
        public static Task<GetRotationDetailResult> InvokeAsync(GetRotationDetailArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRotationDetailResult>("tencentcloud:Ssm/getRotationDetail:getRotationDetail", args ?? new GetRotationDetailArgs(), options.WithDefaults());

        public static Output<GetRotationDetailResult> Invoke(GetRotationDetailInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRotationDetailResult>("tencentcloud:Ssm/getRotationDetail:getRotationDetail", args ?? new GetRotationDetailInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRotationDetailArgs : global::Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("secretName", required: true)]
        public string SecretName { get; set; } = null!;

        public GetRotationDetailArgs()
        {
        }
        public static new GetRotationDetailArgs Empty => new GetRotationDetailArgs();
    }

    public sealed class GetRotationDetailInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("secretName", required: true)]
        public Input<string> SecretName { get; set; } = null!;

        public GetRotationDetailInvokeArgs()
        {
        }
        public static new GetRotationDetailInvokeArgs Empty => new GetRotationDetailInvokeArgs();
    }


    [OutputType]
    public sealed class GetRotationDetailResult
    {
        public readonly bool EnableRotation;
        public readonly int Frequency;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string LatestRotateTime;
        public readonly string NextRotateBeginTime;
        public readonly string? ResultOutputFile;
        public readonly string SecretName;

        [OutputConstructor]
        private GetRotationDetailResult(
            bool enableRotation,

            int frequency,

            string id,

            string latestRotateTime,

            string nextRotateBeginTime,

            string? resultOutputFile,

            string secretName)
        {
            EnableRotation = enableRotation;
            Frequency = frequency;
            Id = id;
            LatestRotateTime = latestRotateTime;
            NextRotateBeginTime = nextRotateBeginTime;
            ResultOutputFile = resultOutputFile;
            SecretName = secretName;
        }
    }
}
