// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class FunctionRuntimeEnvironment extends pulumi.CustomResource {
    /**
     * Get an existing FunctionRuntimeEnvironment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FunctionRuntimeEnvironmentState, opts?: pulumi.CustomResourceOptions): FunctionRuntimeEnvironment {
        return new FunctionRuntimeEnvironment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tencentcloud:Teo/functionRuntimeEnvironment:FunctionRuntimeEnvironment';

    /**
     * Returns true if the given object is an instance of FunctionRuntimeEnvironment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FunctionRuntimeEnvironment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FunctionRuntimeEnvironment.__pulumiType;
    }

    /**
     * The environment variable list.
     */
    public readonly environmentVariables!: pulumi.Output<outputs.Teo.FunctionRuntimeEnvironmentEnvironmentVariable[]>;
    /**
     * ID of the Function.
     */
    public readonly functionId!: pulumi.Output<string>;
    /**
     * ID of the site.
     */
    public readonly zoneId!: pulumi.Output<string>;

    /**
     * Create a FunctionRuntimeEnvironment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FunctionRuntimeEnvironmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FunctionRuntimeEnvironmentArgs | FunctionRuntimeEnvironmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FunctionRuntimeEnvironmentState | undefined;
            resourceInputs["environmentVariables"] = state ? state.environmentVariables : undefined;
            resourceInputs["functionId"] = state ? state.functionId : undefined;
            resourceInputs["zoneId"] = state ? state.zoneId : undefined;
        } else {
            const args = argsOrState as FunctionRuntimeEnvironmentArgs | undefined;
            if ((!args || args.environmentVariables === undefined) && !opts.urn) {
                throw new Error("Missing required property 'environmentVariables'");
            }
            if ((!args || args.functionId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'functionId'");
            }
            if ((!args || args.zoneId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zoneId'");
            }
            resourceInputs["environmentVariables"] = args ? args.environmentVariables : undefined;
            resourceInputs["functionId"] = args ? args.functionId : undefined;
            resourceInputs["zoneId"] = args ? args.zoneId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FunctionRuntimeEnvironment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FunctionRuntimeEnvironment resources.
 */
export interface FunctionRuntimeEnvironmentState {
    /**
     * The environment variable list.
     */
    environmentVariables?: pulumi.Input<pulumi.Input<inputs.Teo.FunctionRuntimeEnvironmentEnvironmentVariable>[]>;
    /**
     * ID of the Function.
     */
    functionId?: pulumi.Input<string>;
    /**
     * ID of the site.
     */
    zoneId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FunctionRuntimeEnvironment resource.
 */
export interface FunctionRuntimeEnvironmentArgs {
    /**
     * The environment variable list.
     */
    environmentVariables: pulumi.Input<pulumi.Input<inputs.Teo.FunctionRuntimeEnvironmentEnvironmentVariable>[]>;
    /**
     * ID of the Function.
     */
    functionId: pulumi.Input<string>;
    /**
     * ID of the site.
     */
    zoneId: pulumi.Input<string>;
}
