// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Oceanus.Outputs
{

    [OutputType]
    public sealed class GetJobSubmissionLogLogContentListResult
    {
        public readonly string ContainerName;
        public readonly string Log;
        public readonly string PkgId;
        public readonly int PkgLogId;
        public readonly int Time;

        [OutputConstructor]
        private GetJobSubmissionLogLogContentListResult(
            string containerName,

            string log,

            string pkgId,

            int pkgLogId,

            int time)
        {
            ContainerName = containerName;
            Log = log;
            PkgId = pkgId;
            PkgLogId = pkgLogId;
            Time = time;
        }
    }
}
