// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Oceanus.Outputs
{

    [OutputType]
    public sealed class GetSavepointListSavepointResult
    {
        public readonly int CreateTime;
        public readonly string Description;
        public readonly int Id;
        public readonly int JobRuntimeId;
        public readonly string Path;
        public readonly int PathStatus;
        public readonly int RecordType;
        public readonly string SerialId;
        public readonly int Size;
        public readonly int Status;
        public readonly int TimeConsuming;
        public readonly int Timeout;
        public readonly int UpdateTime;
        public readonly int VersionId;

        [OutputConstructor]
        private GetSavepointListSavepointResult(
            int createTime,

            string description,

            int id,

            int jobRuntimeId,

            string path,

            int pathStatus,

            int recordType,

            string serialId,

            int size,

            int status,

            int timeConsuming,

            int timeout,

            int updateTime,

            int versionId)
        {
            CreateTime = createTime;
            Description = description;
            Id = id;
            JobRuntimeId = jobRuntimeId;
            Path = path;
            PathStatus = pathStatus;
            RecordType = recordType;
            SerialId = serialId;
            Size = size;
            Status = status;
            TimeConsuming = timeConsuming;
            Timeout = timeout;
            UpdateTime = updateTime;
            VersionId = versionId;
        }
    }
}
