// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Oceanus.Outputs
{

    [OutputType]
    public sealed class GetWorkSpacesWorkSpaceSetItemClusterGroupSetItemResult
    {
        public readonly int AppId;
        public readonly string ClusterId;
        public readonly string CreateTime;
        public readonly string CreatorUin;
        public readonly int CuMem;
        public readonly int CuNum;
        public readonly double FreeCu;
        public readonly int FreeCuNum;
        public readonly string Name;
        public readonly int NetEnvironmentType;
        public readonly string OwnerUin;
        public readonly int PayMode;
        public readonly string Region;
        public readonly string Remark;
        public readonly double RunningCu;
        public readonly int Status;
        public readonly string StatusDesc;
        public readonly string UpdateTime;
        public readonly string Zone;

        [OutputConstructor]
        private GetWorkSpacesWorkSpaceSetItemClusterGroupSetItemResult(
            int appId,

            string clusterId,

            string createTime,

            string creatorUin,

            int cuMem,

            int cuNum,

            double freeCu,

            int freeCuNum,

            string name,

            int netEnvironmentType,

            string ownerUin,

            int payMode,

            string region,

            string remark,

            double runningCu,

            int status,

            string statusDesc,

            string updateTime,

            string zone)
        {
            AppId = appId;
            ClusterId = clusterId;
            CreateTime = createTime;
            CreatorUin = creatorUin;
            CuMem = cuMem;
            CuNum = cuNum;
            FreeCu = freeCu;
            FreeCuNum = freeCuNum;
            Name = name;
            NetEnvironmentType = netEnvironmentType;
            OwnerUin = ownerUin;
            PayMode = payMode;
            Region = region;
            Remark = remark;
            RunningCu = runningCu;
            Status = status;
            StatusDesc = statusDesc;
            UpdateTime = updateTime;
            Zone = zone;
        }
    }
}
