// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Oceanus.Outputs
{

    [OutputType]
    public sealed class JobConfigExpertModeConfigurationJobGraphNode
    {
        public readonly string Description;
        public readonly int Id;
        public readonly string Name;
        public readonly int Parallelism;

        [OutputConstructor]
        private JobConfigExpertModeConfigurationJobGraphNode(
            string description,

            int id,

            string name,

            int parallelism)
        {
            Description = description;
            Id = id;
            Name = name;
            Parallelism = parallelism;
        }
    }
}
