// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Oceanus.Outputs
{

    [OutputType]
    public sealed class JobConfigExpertModeConfigurationJobGraph
    {
        public readonly ImmutableArray<Outputs.JobConfigExpertModeConfigurationJobGraphEdge> Edges;
        public readonly ImmutableArray<Outputs.JobConfigExpertModeConfigurationJobGraphNode> Nodes;

        [OutputConstructor]
        private JobConfigExpertModeConfigurationJobGraph(
            ImmutableArray<Outputs.JobConfigExpertModeConfigurationJobGraphEdge> edges,

            ImmutableArray<Outputs.JobConfigExpertModeConfigurationJobGraphNode> nodes)
        {
            Edges = edges;
            Nodes = nodes;
        }
    }
}
