// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Thpc.Inputs
{

    public sealed class WorkspacesEnhancedServiceGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("automationService")]
        public Input<Inputs.WorkspacesEnhancedServiceAutomationServiceGetArgs>? AutomationService { get; set; }

        [Input("monitorService")]
        public Input<Inputs.WorkspacesEnhancedServiceMonitorServiceGetArgs>? MonitorService { get; set; }

        [Input("securityService")]
        public Input<Inputs.WorkspacesEnhancedServiceSecurityServiceGetArgs>? SecurityService { get; set; }

        public WorkspacesEnhancedServiceGetArgs()
        {
        }
        public static new WorkspacesEnhancedServiceGetArgs Empty => new WorkspacesEnhancedServiceGetArgs();
    }
}
