// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Thpc.Inputs
{

    public sealed class WorkspacesSystemDiskGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("diskId")]
        public Input<string>? DiskId { get; set; }

        [Input("diskSize")]
        public Input<int>? DiskSize { get; set; }

        [Input("diskType")]
        public Input<string>? DiskType { get; set; }

        public WorkspacesSystemDiskGetArgs()
        {
        }
        public static new WorkspacesSystemDiskGetArgs Empty => new WorkspacesSystemDiskGetArgs();
    }
}
