// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Thpc.Inputs
{

    public sealed class WorkspacesInternetAccessibleArgs : global::Pulumi.ResourceArgs
    {
        [Input("bandwidthPackageId")]
        public Input<string>? BandwidthPackageId { get; set; }

        [Input("internetChargeType")]
        public Input<string>? InternetChargeType { get; set; }

        [Input("internetMaxBandwidthOut")]
        public Input<int>? InternetMaxBandwidthOut { get; set; }

        [Input("publicIpAssigned")]
        public Input<bool>? PublicIpAssigned { get; set; }

        public WorkspacesInternetAccessibleArgs()
        {
        }
        public static new WorkspacesInternetAccessibleArgs Empty => new WorkspacesInternetAccessibleArgs();
    }
}
