// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cwp.Outputs
{

    [OutputType]
    public sealed class GetMachinesSimpleMachineRegionInfoResult
    {
        public readonly string Region;
        public readonly string RegionCode;
        public readonly int RegionId;
        public readonly string RegionName;
        public readonly string RegionNameEn;

        [OutputConstructor]
        private GetMachinesSimpleMachineRegionInfoResult(
            string region,

            string regionCode,

            int regionId,

            string regionName,

            string regionNameEn)
        {
            Region = region;
            RegionCode = regionCode;
            RegionId = regionId;
            RegionName = regionName;
            RegionNameEn = regionNameEn;
        }
    }
}
