// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Waf.Inputs
{

    public sealed class ClbDomainLoadBalancerSetGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("listenerId", required: true)]
        public Input<string> ListenerId { get; set; } = null!;

        [Input("listenerName", required: true)]
        public Input<string> ListenerName { get; set; } = null!;

        [Input("loadBalancerId", required: true)]
        public Input<string> LoadBalancerId { get; set; } = null!;

        [Input("loadBalancerName", required: true)]
        public Input<string> LoadBalancerName { get; set; } = null!;

        [Input("loadBalancerType")]
        public Input<string>? LoadBalancerType { get; set; }

        [Input("numericalVpcId")]
        public Input<int>? NumericalVpcId { get; set; }

        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        [Input("vip", required: true)]
        public Input<string> Vip { get; set; } = null!;

        [Input("vport", required: true)]
        public Input<int> Vport { get; set; } = null!;

        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public ClbDomainLoadBalancerSetGetArgs()
        {
        }
        public static new ClbDomainLoadBalancerSetGetArgs Empty => new ClbDomainLoadBalancerSetGetArgs();
    }
}
