// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ssl

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDescribeManagerDetail(ctx *pulumi.Context, args *GetDescribeManagerDetailArgs, opts ...pulumi.InvokeOption) (*GetDescribeManagerDetailResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDescribeManagerDetailResult
	err := ctx.Invoke("tencentcloud:Ssl/getDescribeManagerDetail:getDescribeManagerDetail", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDescribeManagerDetail.
type GetDescribeManagerDetailArgs struct {
	ManagerId        int     `pulumi:"managerId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getDescribeManagerDetail.
type GetDescribeManagerDetailResult struct {
	CompanyId        int                                   `pulumi:"companyId"`
	CompanyInfos     []GetDescribeManagerDetailCompanyInfo `pulumi:"companyInfos"`
	ContactFirstName string                                `pulumi:"contactFirstName"`
	ContactLastName  string                                `pulumi:"contactLastName"`
	ContactMail      string                                `pulumi:"contactMail"`
	ContactPhone     string                                `pulumi:"contactPhone"`
	ContactPosition  string                                `pulumi:"contactPosition"`
	CreateTime       string                                `pulumi:"createTime"`
	ExpireTime       string                                `pulumi:"expireTime"`
	// The provider-assigned unique ID for this managed resource.
	Id                string  `pulumi:"id"`
	ManagerDepartment string  `pulumi:"managerDepartment"`
	ManagerFirstName  string  `pulumi:"managerFirstName"`
	ManagerId         int     `pulumi:"managerId"`
	ManagerLastName   string  `pulumi:"managerLastName"`
	ManagerMail       string  `pulumi:"managerMail"`
	ManagerPhone      string  `pulumi:"managerPhone"`
	ManagerPosition   string  `pulumi:"managerPosition"`
	ResultOutputFile  *string `pulumi:"resultOutputFile"`
	Status            string  `pulumi:"status"`
	VerifyTime        string  `pulumi:"verifyTime"`
}

func GetDescribeManagerDetailOutput(ctx *pulumi.Context, args GetDescribeManagerDetailOutputArgs, opts ...pulumi.InvokeOption) GetDescribeManagerDetailResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDescribeManagerDetailResult, error) {
			args := v.(GetDescribeManagerDetailArgs)
			r, err := GetDescribeManagerDetail(ctx, &args, opts...)
			var s GetDescribeManagerDetailResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDescribeManagerDetailResultOutput)
}

// A collection of arguments for invoking getDescribeManagerDetail.
type GetDescribeManagerDetailOutputArgs struct {
	ManagerId        pulumi.IntInput       `pulumi:"managerId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetDescribeManagerDetailOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDescribeManagerDetailArgs)(nil)).Elem()
}

// A collection of values returned by getDescribeManagerDetail.
type GetDescribeManagerDetailResultOutput struct{ *pulumi.OutputState }

func (GetDescribeManagerDetailResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDescribeManagerDetailResult)(nil)).Elem()
}

func (o GetDescribeManagerDetailResultOutput) ToGetDescribeManagerDetailResultOutput() GetDescribeManagerDetailResultOutput {
	return o
}

func (o GetDescribeManagerDetailResultOutput) ToGetDescribeManagerDetailResultOutputWithContext(ctx context.Context) GetDescribeManagerDetailResultOutput {
	return o
}

func (o GetDescribeManagerDetailResultOutput) CompanyId() pulumi.IntOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) int { return v.CompanyId }).(pulumi.IntOutput)
}

func (o GetDescribeManagerDetailResultOutput) CompanyInfos() GetDescribeManagerDetailCompanyInfoArrayOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) []GetDescribeManagerDetailCompanyInfo { return v.CompanyInfos }).(GetDescribeManagerDetailCompanyInfoArrayOutput)
}

func (o GetDescribeManagerDetailResultOutput) ContactFirstName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ContactFirstName }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ContactLastName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ContactLastName }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ContactMail() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ContactMail }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ContactPhone() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ContactPhone }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ContactPosition() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ContactPosition }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.CreateTime }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ExpireTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ExpireTime }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDescribeManagerDetailResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ManagerDepartment() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ManagerDepartment }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ManagerFirstName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ManagerFirstName }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ManagerId() pulumi.IntOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) int { return v.ManagerId }).(pulumi.IntOutput)
}

func (o GetDescribeManagerDetailResultOutput) ManagerLastName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ManagerLastName }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ManagerMail() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ManagerMail }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ManagerPhone() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ManagerPhone }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ManagerPosition() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.ManagerPosition }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetDescribeManagerDetailResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetDescribeManagerDetailResultOutput) VerifyTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeManagerDetailResult) string { return v.VerifyTime }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDescribeManagerDetailResultOutput{})
}
