// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dnspod
{
    public static class GetRecordLineList
    {
        public static Task<GetRecordLineListResult> InvokeAsync(GetRecordLineListArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRecordLineListResult>("tencentcloud:Dnspod/getRecordLineList:getRecordLineList", args ?? new GetRecordLineListArgs(), options.WithDefaults());

        public static Output<GetRecordLineListResult> Invoke(GetRecordLineListInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRecordLineListResult>("tencentcloud:Dnspod/getRecordLineList:getRecordLineList", args ?? new GetRecordLineListInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRecordLineListArgs : global::Pulumi.InvokeArgs
    {
        [Input("domain", required: true)]
        public string Domain { get; set; } = null!;

        [Input("domainGrade", required: true)]
        public string DomainGrade { get; set; } = null!;

        [Input("domainId")]
        public int? DomainId { get; set; }

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public GetRecordLineListArgs()
        {
        }
        public static new GetRecordLineListArgs Empty => new GetRecordLineListArgs();
    }

    public sealed class GetRecordLineListInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("domainGrade", required: true)]
        public Input<string> DomainGrade { get; set; } = null!;

        [Input("domainId")]
        public Input<int>? DomainId { get; set; }

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public GetRecordLineListInvokeArgs()
        {
        }
        public static new GetRecordLineListInvokeArgs Empty => new GetRecordLineListInvokeArgs();
    }


    [OutputType]
    public sealed class GetRecordLineListResult
    {
        public readonly string Domain;
        public readonly string DomainGrade;
        public readonly int? DomainId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetRecordLineListLineGroupListResult> LineGroupLists;
        public readonly ImmutableArray<Outputs.GetRecordLineListLineListResult> LineLists;
        public readonly string? ResultOutputFile;

        [OutputConstructor]
        private GetRecordLineListResult(
            string domain,

            string domainGrade,

            int? domainId,

            string id,

            ImmutableArray<Outputs.GetRecordLineListLineGroupListResult> lineGroupLists,

            ImmutableArray<Outputs.GetRecordLineListLineListResult> lineLists,

            string? resultOutputFile)
        {
            Domain = domain;
            DomainGrade = domainGrade;
            DomainId = domainId;
            Id = id;
            LineGroupLists = lineGroupLists;
            LineLists = lineLists;
            ResultOutputFile = resultOutputFile;
        }
    }
}
