// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cam

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAccountSummary(ctx *pulumi.Context, args *GetAccountSummaryArgs, opts ...pulumi.InvokeOption) (*GetAccountSummaryResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAccountSummaryResult
	err := ctx.Invoke("tencentcloud:Cam/getAccountSummary:getAccountSummary", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccountSummary.
type GetAccountSummaryArgs struct {
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getAccountSummary.
type GetAccountSummaryResult struct {
	Group int `pulumi:"group"`
	// The provider-assigned unique ID for this managed resource.
	Id                string  `pulumi:"id"`
	IdentityProviders int     `pulumi:"identityProviders"`
	Member            int     `pulumi:"member"`
	Policies          int     `pulumi:"policies"`
	ResultOutputFile  *string `pulumi:"resultOutputFile"`
	Roles             int     `pulumi:"roles"`
	User              int     `pulumi:"user"`
}

func GetAccountSummaryOutput(ctx *pulumi.Context, args GetAccountSummaryOutputArgs, opts ...pulumi.InvokeOption) GetAccountSummaryResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAccountSummaryResult, error) {
			args := v.(GetAccountSummaryArgs)
			r, err := GetAccountSummary(ctx, &args, opts...)
			var s GetAccountSummaryResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAccountSummaryResultOutput)
}

// A collection of arguments for invoking getAccountSummary.
type GetAccountSummaryOutputArgs struct {
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetAccountSummaryOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccountSummaryArgs)(nil)).Elem()
}

// A collection of values returned by getAccountSummary.
type GetAccountSummaryResultOutput struct{ *pulumi.OutputState }

func (GetAccountSummaryResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccountSummaryResult)(nil)).Elem()
}

func (o GetAccountSummaryResultOutput) ToGetAccountSummaryResultOutput() GetAccountSummaryResultOutput {
	return o
}

func (o GetAccountSummaryResultOutput) ToGetAccountSummaryResultOutputWithContext(ctx context.Context) GetAccountSummaryResultOutput {
	return o
}

func (o GetAccountSummaryResultOutput) Group() pulumi.IntOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) int { return v.Group }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAccountSummaryResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAccountSummaryResultOutput) IdentityProviders() pulumi.IntOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) int { return v.IdentityProviders }).(pulumi.IntOutput)
}

func (o GetAccountSummaryResultOutput) Member() pulumi.IntOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) int { return v.Member }).(pulumi.IntOutput)
}

func (o GetAccountSummaryResultOutput) Policies() pulumi.IntOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) int { return v.Policies }).(pulumi.IntOutput)
}

func (o GetAccountSummaryResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetAccountSummaryResultOutput) Roles() pulumi.IntOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) int { return v.Roles }).(pulumi.IntOutput)
}

func (o GetAccountSummaryResultOutput) User() pulumi.IntOutput {
	return o.ApplyT(func(v GetAccountSummaryResult) int { return v.User }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAccountSummaryResultOutput{})
}
