// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package emr

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAutoScaleRecords(ctx *pulumi.Context, args *GetAutoScaleRecordsArgs, opts ...pulumi.InvokeOption) (*GetAutoScaleRecordsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAutoScaleRecordsResult
	err := ctx.Invoke("tencentcloud:Emr/getAutoScaleRecords:getAutoScaleRecords", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAutoScaleRecords.
type GetAutoScaleRecordsArgs struct {
	Filters          []GetAutoScaleRecordsFilter `pulumi:"filters"`
	InstanceId       string                      `pulumi:"instanceId"`
	ResultOutputFile *string                     `pulumi:"resultOutputFile"`
}

// A collection of values returned by getAutoScaleRecords.
type GetAutoScaleRecordsResult struct {
	Filters []GetAutoScaleRecordsFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                          `pulumi:"id"`
	InstanceId       string                          `pulumi:"instanceId"`
	RecordLists      []GetAutoScaleRecordsRecordList `pulumi:"recordLists"`
	ResultOutputFile *string                         `pulumi:"resultOutputFile"`
}

func GetAutoScaleRecordsOutput(ctx *pulumi.Context, args GetAutoScaleRecordsOutputArgs, opts ...pulumi.InvokeOption) GetAutoScaleRecordsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAutoScaleRecordsResult, error) {
			args := v.(GetAutoScaleRecordsArgs)
			r, err := GetAutoScaleRecords(ctx, &args, opts...)
			var s GetAutoScaleRecordsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAutoScaleRecordsResultOutput)
}

// A collection of arguments for invoking getAutoScaleRecords.
type GetAutoScaleRecordsOutputArgs struct {
	Filters          GetAutoScaleRecordsFilterArrayInput `pulumi:"filters"`
	InstanceId       pulumi.StringInput                  `pulumi:"instanceId"`
	ResultOutputFile pulumi.StringPtrInput               `pulumi:"resultOutputFile"`
}

func (GetAutoScaleRecordsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAutoScaleRecordsArgs)(nil)).Elem()
}

// A collection of values returned by getAutoScaleRecords.
type GetAutoScaleRecordsResultOutput struct{ *pulumi.OutputState }

func (GetAutoScaleRecordsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAutoScaleRecordsResult)(nil)).Elem()
}

func (o GetAutoScaleRecordsResultOutput) ToGetAutoScaleRecordsResultOutput() GetAutoScaleRecordsResultOutput {
	return o
}

func (o GetAutoScaleRecordsResultOutput) ToGetAutoScaleRecordsResultOutputWithContext(ctx context.Context) GetAutoScaleRecordsResultOutput {
	return o
}

func (o GetAutoScaleRecordsResultOutput) Filters() GetAutoScaleRecordsFilterArrayOutput {
	return o.ApplyT(func(v GetAutoScaleRecordsResult) []GetAutoScaleRecordsFilter { return v.Filters }).(GetAutoScaleRecordsFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAutoScaleRecordsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAutoScaleRecordsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAutoScaleRecordsResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAutoScaleRecordsResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetAutoScaleRecordsResultOutput) RecordLists() GetAutoScaleRecordsRecordListArrayOutput {
	return o.ApplyT(func(v GetAutoScaleRecordsResult) []GetAutoScaleRecordsRecordList { return v.RecordLists }).(GetAutoScaleRecordsRecordListArrayOutput)
}

func (o GetAutoScaleRecordsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAutoScaleRecordsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAutoScaleRecordsResultOutput{})
}
