// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Dlc.Outputs
{

    [OutputType]
    public sealed class GetDescribeWorkGroupInfoWorkGroupInfoResult
    {
        public readonly ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoDataPolicyInfoResult> DataPolicyInfos;
        public readonly ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoEnginePolicyInfoResult> EnginePolicyInfos;
        public readonly ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoRowFilterInfoResult> RowFilterInfos;
        public readonly string Type;
        public readonly ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoUserInfoResult> UserInfos;
        public readonly string WorkGroupDescription;
        public readonly int WorkGroupId;
        public readonly string WorkGroupName;

        [OutputConstructor]
        private GetDescribeWorkGroupInfoWorkGroupInfoResult(
            ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoDataPolicyInfoResult> dataPolicyInfos,

            ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoEnginePolicyInfoResult> enginePolicyInfos,

            ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoRowFilterInfoResult> rowFilterInfos,

            string type,

            ImmutableArray<Outputs.GetDescribeWorkGroupInfoWorkGroupInfoUserInfoResult> userInfos,

            string workGroupDescription,

            int workGroupId,

            string workGroupName)
        {
            DataPolicyInfos = dataPolicyInfos;
            EnginePolicyInfos = enginePolicyInfos;
            RowFilterInfos = rowFilterInfos;
            Type = type;
            UserInfos = userInfos;
            WorkGroupDescription = workGroupDescription;
            WorkGroupId = workGroupId;
            WorkGroupName = workGroupName;
        }
    }
}
