// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Trocket.Inputs
{

    public sealed class RocketmqInstanceIpRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("allow", required: true)]
        public Input<bool> Allow { get; set; } = null!;

        [Input("ip", required: true)]
        public Input<string> Ip { get; set; } = null!;

        [Input("remark", required: true)]
        public Input<string> Remark { get; set; } = null!;

        public RocketmqInstanceIpRuleArgs()
        {
        }
        public static new RocketmqInstanceIpRuleArgs Empty => new RocketmqInstanceIpRuleArgs();
    }
}
