// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dnspod

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetRecordLineList(ctx *pulumi.Context, args *GetRecordLineListArgs, opts ...pulumi.InvokeOption) (*GetRecordLineListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetRecordLineListResult
	err := ctx.Invoke("tencentcloud:Dnspod/getRecordLineList:getRecordLineList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRecordLineList.
type GetRecordLineListArgs struct {
	Domain           string  `pulumi:"domain"`
	DomainGrade      string  `pulumi:"domainGrade"`
	DomainId         *int    `pulumi:"domainId"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getRecordLineList.
type GetRecordLineListResult struct {
	Domain      string `pulumi:"domain"`
	DomainGrade string `pulumi:"domainGrade"`
	DomainId    *int   `pulumi:"domainId"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                           `pulumi:"id"`
	LineGroupLists   []GetRecordLineListLineGroupList `pulumi:"lineGroupLists"`
	LineLists        []GetRecordLineListLineList      `pulumi:"lineLists"`
	ResultOutputFile *string                          `pulumi:"resultOutputFile"`
}

func GetRecordLineListOutput(ctx *pulumi.Context, args GetRecordLineListOutputArgs, opts ...pulumi.InvokeOption) GetRecordLineListResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetRecordLineListResult, error) {
			args := v.(GetRecordLineListArgs)
			r, err := GetRecordLineList(ctx, &args, opts...)
			var s GetRecordLineListResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetRecordLineListResultOutput)
}

// A collection of arguments for invoking getRecordLineList.
type GetRecordLineListOutputArgs struct {
	Domain           pulumi.StringInput    `pulumi:"domain"`
	DomainGrade      pulumi.StringInput    `pulumi:"domainGrade"`
	DomainId         pulumi.IntPtrInput    `pulumi:"domainId"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetRecordLineListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRecordLineListArgs)(nil)).Elem()
}

// A collection of values returned by getRecordLineList.
type GetRecordLineListResultOutput struct{ *pulumi.OutputState }

func (GetRecordLineListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRecordLineListResult)(nil)).Elem()
}

func (o GetRecordLineListResultOutput) ToGetRecordLineListResultOutput() GetRecordLineListResultOutput {
	return o
}

func (o GetRecordLineListResultOutput) ToGetRecordLineListResultOutputWithContext(ctx context.Context) GetRecordLineListResultOutput {
	return o
}

func (o GetRecordLineListResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetRecordLineListResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o GetRecordLineListResultOutput) DomainGrade() pulumi.StringOutput {
	return o.ApplyT(func(v GetRecordLineListResult) string { return v.DomainGrade }).(pulumi.StringOutput)
}

func (o GetRecordLineListResultOutput) DomainId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetRecordLineListResult) *int { return v.DomainId }).(pulumi.IntPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetRecordLineListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetRecordLineListResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetRecordLineListResultOutput) LineGroupLists() GetRecordLineListLineGroupListArrayOutput {
	return o.ApplyT(func(v GetRecordLineListResult) []GetRecordLineListLineGroupList { return v.LineGroupLists }).(GetRecordLineListLineGroupListArrayOutput)
}

func (o GetRecordLineListResultOutput) LineLists() GetRecordLineListLineListArrayOutput {
	return o.ApplyT(func(v GetRecordLineListResult) []GetRecordLineListLineList { return v.LineLists }).(GetRecordLineListLineListArrayOutput)
}

func (o GetRecordLineListResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetRecordLineListResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetRecordLineListResultOutput{})
}
