// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dnspod

import (
	"context"
	"reflect"

	"github.com/matrixorigin/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetRecordType(ctx *pulumi.Context, args *GetRecordTypeArgs, opts ...pulumi.InvokeOption) (*GetRecordTypeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetRecordTypeResult
	err := ctx.Invoke("tencentcloud:Dnspod/getRecordType:getRecordType", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRecordType.
type GetRecordTypeArgs struct {
	DomainGrade      string  `pulumi:"domainGrade"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getRecordType.
type GetRecordTypeResult struct {
	DomainGrade string `pulumi:"domainGrade"`
	// The provider-assigned unique ID for this managed resource.
	Id               string   `pulumi:"id"`
	ResultOutputFile *string  `pulumi:"resultOutputFile"`
	TypeLists        []string `pulumi:"typeLists"`
}

func GetRecordTypeOutput(ctx *pulumi.Context, args GetRecordTypeOutputArgs, opts ...pulumi.InvokeOption) GetRecordTypeResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetRecordTypeResult, error) {
			args := v.(GetRecordTypeArgs)
			r, err := GetRecordType(ctx, &args, opts...)
			var s GetRecordTypeResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetRecordTypeResultOutput)
}

// A collection of arguments for invoking getRecordType.
type GetRecordTypeOutputArgs struct {
	DomainGrade      pulumi.StringInput    `pulumi:"domainGrade"`
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetRecordTypeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRecordTypeArgs)(nil)).Elem()
}

// A collection of values returned by getRecordType.
type GetRecordTypeResultOutput struct{ *pulumi.OutputState }

func (GetRecordTypeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRecordTypeResult)(nil)).Elem()
}

func (o GetRecordTypeResultOutput) ToGetRecordTypeResultOutput() GetRecordTypeResultOutput {
	return o
}

func (o GetRecordTypeResultOutput) ToGetRecordTypeResultOutputWithContext(ctx context.Context) GetRecordTypeResultOutput {
	return o
}

func (o GetRecordTypeResultOutput) DomainGrade() pulumi.StringOutput {
	return o.ApplyT(func(v GetRecordTypeResult) string { return v.DomainGrade }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetRecordTypeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetRecordTypeResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetRecordTypeResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetRecordTypeResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetRecordTypeResultOutput) TypeLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetRecordTypeResult) []string { return v.TypeLists }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetRecordTypeResultOutput{})
}
