// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Css.Outputs
{

    [OutputType]
    public sealed class GetMonitorReportMpsResultResult
    {
        public readonly ImmutableArray<string> AiAsrResults;
        public readonly ImmutableArray<string> AiOcrResults;

        [OutputConstructor]
        private GetMonitorReportMpsResultResult(
            ImmutableArray<string> aiAsrResults,

            ImmutableArray<string> aiOcrResults)
        {
            AiAsrResults = aiAsrResults;
            AiOcrResults = aiOcrResults;
        }
    }
}
