// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Teo.Outputs
{

    [OutputType]
    public sealed class RealtimeLogDeliveryLogFormat
    {
        public readonly string? BatchPrefix;
        public readonly string? BatchSuffix;
        public readonly string? FieldDelimiter;
        public readonly string FormatType;
        public readonly string? RecordDelimiter;
        public readonly string? RecordPrefix;
        public readonly string? RecordSuffix;

        [OutputConstructor]
        private RealtimeLogDeliveryLogFormat(
            string? batchPrefix,

            string? batchSuffix,

            string? fieldDelimiter,

            string formatType,

            string? recordDelimiter,

            string? recordPrefix,

            string? recordSuffix)
        {
            BatchPrefix = batchPrefix;
            BatchSuffix = batchSuffix;
            FieldDelimiter = fieldDelimiter;
            FormatType = formatType;
            RecordDelimiter = recordDelimiter;
            RecordPrefix = recordPrefix;
            RecordSuffix = recordSuffix;
        }
    }
}
