// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Elasticsearch.Outputs
{

    [OutputType]
    public sealed class GetInstanceOperationsOperationDetailResult
    {
        public readonly ImmutableArray<Outputs.GetInstanceOperationsOperationDetailNewInfoResult> NewInfos;
        public readonly ImmutableArray<Outputs.GetInstanceOperationsOperationDetailOldInfoResult> OldInfos;

        [OutputConstructor]
        private GetInstanceOperationsOperationDetailResult(
            ImmutableArray<Outputs.GetInstanceOperationsOperationDetailNewInfoResult> newInfos,

            ImmutableArray<Outputs.GetInstanceOperationsOperationDetailOldInfoResult> oldInfos)
        {
            NewInfos = newInfos;
            OldInfos = oldInfos;
        }
    }
}
