// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Elasticsearch.Outputs
{

    [OutputType]
    public sealed class GetLogstashInstanceOperationsOperationTaskSubTaskResult
    {
        public readonly string ErrMsg;
        public readonly ImmutableArray<string> FailedIndices;
        public readonly string FinishTime;
        public readonly int Level;
        public readonly string Name;
        public readonly bool Result;
        public readonly int Status;
        public readonly string Type;

        [OutputConstructor]
        private GetLogstashInstanceOperationsOperationTaskSubTaskResult(
            string errMsg,

            ImmutableArray<string> failedIndices,

            string finishTime,

            int level,

            string name,

            bool result,

            int status,

            string type)
        {
            ErrMsg = errMsg;
            FailedIndices = failedIndices;
            FinishTime = finishTime;
            Level = level;
            Name = name;
            Result = result;
            Status = status;
            Type = type;
        }
    }
}
