// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Elasticsearch.Outputs
{

    [OutputType]
    public sealed class InstanceCosBackup
    {
        public readonly string BackupTime;
        public readonly bool IsAutoBackup;

        [OutputConstructor]
        private InstanceCosBackup(
            string backupTime,

            bool isAutoBackup)
        {
            BackupTime = backupTime;
            IsAutoBackup = isAutoBackup;
        }
    }
}
