// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Antiddos.Outputs
{

    [OutputType]
    public sealed class GetListListenerLayer4ListenerInstanceDetailRuleResult
    {
        public readonly string Cname;
        public readonly ImmutableArray<string> EipLists;
        public readonly string InstanceId;

        [OutputConstructor]
        private GetListListenerLayer4ListenerInstanceDetailRuleResult(
            string cname,

            ImmutableArray<string> eipLists,

            string instanceId)
        {
            Cname = cname;
            EipLists = eipLists;
            InstanceId = instanceId;
        }
    }
}
