// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getDescribeManagers(args: GetDescribeManagersArgs, opts?: pulumi.InvokeOptions): Promise<GetDescribeManagersResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Ssl/getDescribeManagers:getDescribeManagers", {
        "companyId": args.companyId,
        "managerMail": args.managerMail,
        "managerName": args.managerName,
        "resultOutputFile": args.resultOutputFile,
        "searchKey": args.searchKey,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getDescribeManagers.
 */
export interface GetDescribeManagersArgs {
    companyId: number;
    managerMail?: string;
    managerName?: string;
    resultOutputFile?: string;
    searchKey?: string;
    status?: string;
}

/**
 * A collection of values returned by getDescribeManagers.
 */
export interface GetDescribeManagersResult {
    readonly companyId: number;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly managerMail?: string;
    readonly managerName?: string;
    readonly managers: outputs.Ssl.GetDescribeManagersManager[];
    readonly resultOutputFile?: string;
    readonly searchKey?: string;
    readonly status?: string;
}
export function getDescribeManagersOutput(args: GetDescribeManagersOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDescribeManagersResult> {
    return pulumi.output(args).apply((a: any) => getDescribeManagers(a, opts))
}

/**
 * A collection of arguments for invoking getDescribeManagers.
 */
export interface GetDescribeManagersOutputArgs {
    companyId: pulumi.Input<number>;
    managerMail?: pulumi.Input<string>;
    managerName?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
    searchKey?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
}
