// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getDescribeHostLighthouseInstanceList(args: GetDescribeHostLighthouseInstanceListArgs, opts?: pulumi.InvokeOptions): Promise<GetDescribeHostLighthouseInstanceListResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Ssl/getDescribeHostLighthouseInstanceList:getDescribeHostLighthouseInstanceList", {
        "certificateId": args.certificateId,
        "filters": args.filters,
        "isCache": args.isCache,
        "resourceType": args.resourceType,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getDescribeHostLighthouseInstanceList.
 */
export interface GetDescribeHostLighthouseInstanceListArgs {
    certificateId: string;
    filters?: inputs.Ssl.GetDescribeHostLighthouseInstanceListFilter[];
    isCache?: number;
    resourceType: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getDescribeHostLighthouseInstanceList.
 */
export interface GetDescribeHostLighthouseInstanceListResult {
    readonly certificateId: string;
    readonly filters?: outputs.Ssl.GetDescribeHostLighthouseInstanceListFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceLists: outputs.Ssl.GetDescribeHostLighthouseInstanceListInstanceList[];
    readonly isCache?: number;
    readonly resourceType: string;
    readonly resultOutputFile?: string;
}
export function getDescribeHostLighthouseInstanceListOutput(args: GetDescribeHostLighthouseInstanceListOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDescribeHostLighthouseInstanceListResult> {
    return pulumi.output(args).apply((a: any) => getDescribeHostLighthouseInstanceList(a, opts))
}

/**
 * A collection of arguments for invoking getDescribeHostLighthouseInstanceList.
 */
export interface GetDescribeHostLighthouseInstanceListOutputArgs {
    certificateId: pulumi.Input<string>;
    filters?: pulumi.Input<pulumi.Input<inputs.Ssl.GetDescribeHostLighthouseInstanceListFilterArgs>[]>;
    isCache?: pulumi.Input<number>;
    resourceType: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
