// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Cfw.Outputs
{

    [OutputType]
    public sealed class GetVpcFwSwitchesSwitchListResult
    {
        public readonly int Enable;
        public readonly int Status;
        public readonly string SwitchId;
        public readonly int SwitchMode;
        public readonly string SwitchName;

        [OutputConstructor]
        private GetVpcFwSwitchesSwitchListResult(
            int enable,

            int status,

            string switchId,

            int switchMode,

            string switchName)
        {
            Enable = enable;
            Status = status;
            SwitchId = switchId;
            SwitchMode = switchMode;
            SwitchName = switchName;
        }
    }
}
