// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getGroupLog(args: GetGroupLogArgs, opts?: pulumi.InvokeOptions): Promise<GetGroupLogResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:Rum/getGroupLog:getGroupLog", {
        "endTime": args.endTime,
        "groupField": args.groupField,
        "orderBy": args.orderBy,
        "projectId": args.projectId,
        "query": args.query,
        "resultOutputFile": args.resultOutputFile,
        "startTime": args.startTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getGroupLog.
 */
export interface GetGroupLogArgs {
    endTime: string;
    groupField: string;
    orderBy: string;
    projectId: number;
    query: string;
    resultOutputFile?: string;
    startTime: string;
}

/**
 * A collection of values returned by getGroupLog.
 */
export interface GetGroupLogResult {
    readonly endTime: string;
    readonly groupField: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly orderBy: string;
    readonly projectId: number;
    readonly query: string;
    readonly result: string;
    readonly resultOutputFile?: string;
    readonly startTime: string;
}
export function getGroupLogOutput(args: GetGroupLogOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGroupLogResult> {
    return pulumi.output(args).apply((a: any) => getGroupLog(a, opts))
}

/**
 * A collection of arguments for invoking getGroupLog.
 */
export interface GetGroupLogOutputArgs {
    endTime: pulumi.Input<string>;
    groupField: pulumi.Input<string>;
    orderBy: pulumi.Input<string>;
    projectId: pulumi.Input<number>;
    query: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
    startTime: pulumi.Input<string>;
}
