// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Identity.Inputs
{

    public sealed class CenterRoleConfigurationPermissionCustomPoliciesAttachmentPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("addTime")]
        public Input<string>? AddTime { get; set; }

        [Input("rolePolicyDocument", required: true)]
        public Input<string> RolePolicyDocument { get; set; } = null!;

        [Input("rolePolicyName", required: true)]
        public Input<string> RolePolicyName { get; set; } = null!;

        [Input("rolePolicyType")]
        public Input<string>? RolePolicyType { get; set; }

        public CenterRoleConfigurationPermissionCustomPoliciesAttachmentPolicyArgs()
        {
        }
        public static new CenterRoleConfigurationPermissionCustomPoliciesAttachmentPolicyArgs Empty => new CenterRoleConfigurationPermissionCustomPoliciesAttachmentPolicyArgs();
    }
}
